### ISSUE TITLE
How to disable WP posts and pages from Search?

### ISSUE THREAD

**Issue by shtefcs** [WebDevStudios/wp-search-with-algolia#1]
Hey guys, first of all, great plugin 👌 . For real, I was searching for Algolia WP plugin for some time, since the original is removed from WP Plugin Dir.

Anyway, I am trying to figure out how to remove standard WP posts, Pages from Search result?

I am using EDD (Easy Digital Download) plugin, which have their own custom post type called **Downloads** and I want to search only Download posts.

Now I have the ability to do it for Autocomplete search https://i.imgur.com/Dp09dm0.png, but I don't see the option when you are actually on the search page for a specific term. Here is a Search page example https://unsold.design/?s=design , and as you can see its shows both standard WP Posts, Pages and then EDD Downloads.

Would like to hear your suggestions.

Peace,

**Comment by marko-stimac** [comment]
Did you try removing post types? https://community.algolia.com/wordpress/filters.html
This should disable indexing of those post types, so if they are already indexed I guess you also have to delete those records from Algolia.

```
add_filter('algolia_post_types_blacklist', 'mb_blacklist_custom_post_type');
function mb_blacklist_custom_post_type( array $blacklist ) {
    $blacklist[] = 'post';
    $blacklist[] = 'page';

    return $blacklist;
}
```

**Comment by shtefcs** [comment]
thank you guys for the response. I paused that project for now, but will definitely use ur suggestion @marko-stimac  @tw2113  .

Peace!

**Comment by richaber** [comment]
@shtefcs I'm going to close this issue, since it appears that your original inquiry has a satisfactory answer.
