### ISSUE TITLE
Support for Woocommerce CTR and Conversion Tracking

### ISSUE THREAD

**Issue by stevethebartender** [WebDevStudios/wp-search-with-algolia#100]
**Is your feature request related to a problem? Please describe.**
Currently I cannot track the success of Algolia searches via CTR or conversion metrics: http://prntscr.com/url6zx

**Describe the solution you'd like**
I would like the ability to add tracking through the plugin, details here:
https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-through-and-conversions/

**Describe alternatives you've considered**
None. I don't have the know-how to implement a feature such as this.

**Comment by Ipstenu** [comment]
I would recommend changing the subject of this to "Support Algolia click and conversion events" since this is a feature of theirs.

The implementation would need to use these:

* search-insights v1.6.2 or later.
* InstantSearch.js v4.8.3 or later

And at the moment, the plugin's on InstantSearchJS 1.12.1 so there's some serious pre-work that needs to happen there :(

**Comment by Dimusan** [comment]
Hi!
I use Algolia in the backend and don't have any analitics except Total Searches. I have tried use code snipets from https://github.com/algolia/search-insights.js, but no succsess. If it is possible to add analitics functionality to the plugin it will be next level of the plugin!

**Comment by richaber** [comment]
[WPSWA version 2.0.0](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/2.0.0) ships with updated Algolia libraries.

Algolia JavaScript API Client version 4.10.3
Algolia InstantSearch.js version 4.25.2
Algolia Autocomplete.js version 0.38.0
Algolia PHP API Client version 3.0.2

That might help you implement click and conversion events on your own, based on @Ipstenu's comment.

As for implementing click and conversion events support directly in WPSWA, I'm not sure if that's a feature that requires a "Premium plan" or not. If it does not, then I'm open to the idea of exploring that.
