### ISSUE TITLE
Pinterest conflicts

### ISSUE THREAD

**Issue by michaeltieso** [WebDevStudios/wp-search-with-algolia#101]
**Describe the bug**
Causes Pinterest to load thumbnails from Algolia instead of the blog post.

**To Reproduce**
1. Enable plugin.
2. Create pin on Pinterest.

**Expected behavior**
Should be loading images from the blog post.

**Screenshots**
<img width="831" alt="Screen Shot 2020-10-02 at 10 45 09 AM" src="https://user-images.githubusercontent.com/1500606/94936581-6d4b6900-049c-11eb-9f2e-bd41cb8a32f2.png">

**Desktop (please complete the following information):**

**Comment by richaber** [comment]
Howdy @michaeltieso,

With the caveat that I can't provide Pinterest specific support...

I visited https://thetravellingmom.ca/skiing-in-western-canada/

I clicked the "Pinterest" icon and saved to a Pinterest "board".

![Screen Shot 2020-10-02 at 12 23 14 PM](https://user-images.githubusercontent.com/5407441/94951948-c8845800-04aa-11eb-9e46-9d7d380367a0.png)
![Screen Shot 2020-10-02 at 12 26 47 PM](https://user-images.githubusercontent.com/5407441/94951973-d043fc80-04aa-11eb-87f5-6f8db20416c7.png)
![Screen Shot 2020-10-02 at 12 26 55 PM](https://user-images.githubusercontent.com/5407441/94951990-d4701a00-04aa-11eb-948b-6d191c07f935.png)
![Screen Shot 2020-10-02 at 12 27 18 PM](https://user-images.githubusercontent.com/5407441/94951999-d803a100-04aa-11eb-8983-5a188c16fd90.png)

I'm not really a Pinterest user, but it appears that worked as expected.

I'm afraid I need more details about the issue you are describing, if I am to determine whethre the issue originates within the WP Search with Algolia plugin itself.

Can you provide the _exact steps_ to recreate the issue?

**Comment by richaber** [comment]
Interesting side note, Pinterest appeared to scrape the title used on the pin from Algolia instead of from the article itself. 🤔

**Comment by richaber** [comment]
Yet, when I visit that exact same pin today, the article headline is displayed on the pin...
![Screen Shot 2020-10-06 at 8 30 15 AM](https://user-images.githubusercontent.com/5407441/95208055-35029e00-07ae-11eb-9eb0-cfd53a94466b.png)

**Comment by richaber** [comment]
Potentially related Pinterest issues:

https://wordpress.org/support/topic/problem-with-algolia-injecting-text-into-pinterest-pins/

https://wordpress.org/support/topic/algolia-injecting-title-into-pinterest-pin/

**Comment by richaber** [comment]
It appears in my testing that this issue presents when using autocomplete.

My current hypothesis is that Pinterest's "scraper" has difficulty parsing past the underscore.js style templates in the header.

I am going to open a PR that moves the autocomplete underscore.js style templates and the config into the footer, which I think will resolve the Pinterest issues that are being reported.

**Comment by richaber** [comment]
To be clear, WP Search with Algolia does not inject any text or images into Pinterest pins.

Some users have reported the text "Hosted Site Search & Discovery for Companies of All Sizes" being used for the Pin title, however, the plugin does not contain that text.

When a "pin" is saved, Pinterest "scrapes" the URL, and parses the markup, Open Graph, and other meta tags that it finds, to determine what text and image to use for the pin.

WP Search with Algolia does not modify any Open Graph or other meta tags in the page.

My testing seems to indicate that this issue may be related specifically to the autocomplete implementation.

When autocomplete is enabled, the plugin adds some underscore.js style templating into the header of the page.

It appears that Pinterest has difficulty parsing past the autocomplete template in the head.

I believe that moving the JS, autocomplete underscore.js template, and config, to the footer of the page _should_ alleviate issues that WP Search with Algolia / Pinterest users are reporting.

**Comment by richaber** [comment]
I believe the [fix/101-pinterest-incompatibility](https://github.com/WebDevStudios/wp-search-with-algolia/tree/fix/101-pinterest-incompatibility) should resolve Pinterest issues for most users, however, I would like to perform a little more testing before release.

**Comment by richaber** [comment]
Testing from my own public facing blog with version 1.4.0:

![Screen Shot 2020-10-06 at 7 47 46 PM](https://user-images.githubusercontent.com/5407441/95275468-2cda4b00-080e-11eb-8ccb-019950eb6c6e.png)

Testing from my own public facing blog with version 1.5.0-dev:

![Screen Shot 2020-10-06 at 7 55 03 PM](https://user-images.githubusercontent.com/5407441/95275481-35cb1c80-080e-11eb-978e-96a88c23542b.png)

**Comment by richaber** [comment]
Verified that autocomplete functions as expected in 1.5.0-dev.

![Screen Shot 2020-10-06 at 8 12 25 PM](https://user-images.githubusercontent.com/5407441/95276255-51372700-0810-11eb-8e0b-a83c83368b31.png)

Verified that instantsearch functions as expected in 1.5.0-dev.

![Screen Shot 2020-10-06 at 8 08 52 PM](https://user-images.githubusercontent.com/5407441/95276079-d3731b80-080f-11eb-90cc-16cb3e95bdb5.png)

**Comment by richaber** [comment]
Worth noting/mentioning that moving the scripts, autocomplete template, and config to the footer might make the `algolia_load_scripts_in_footer` hook unnecessary. It was introduced in 1.3.0 as a way for devs to load the Algolia JS libs in the footer for performance reasons. I've defaulted it to `true` in 1.5.0-dev as part of moving everything into the footer that the Pinterest scraper might choke on.

**Comment by kakashigr** [comment]
Apparently if you remove this code from autocomplete.php, everything works correctly:

`jQuery(document).on("click", ".algolia-powered-by-link", function (e) {
	  e.preventDefault();
	  window.location = "https://www.algolia.com/?utm_source=WordPress&utm_medium=extension&utm_content=" + 
          window.location.hostname + "&utm_campaign=poweredby"; 
});`

**Comment by richaber** [comment]
Thank you for the additional information @kakashigr 

I'm not sure why Pinterest's scraper follows the algolia-powered-by-link offsite and pulls data from the Algolia domain. That is clearly an issue with Pinterest that we can't control.

However, moving the autocomplete template output that contains that link to the footer, appears to resolve the issue in my testing.

![Screen Shot 2020-10-07 at 8 36 02 AM](https://user-images.githubusercontent.com/5407441/95338370-765f8000-0878-11eb-93d7-3878c38adf6f.png)

![Screen Shot 2020-10-07 at 8 36 27 AM](https://user-images.githubusercontent.com/5407441/95338366-765f8000-0878-11eb-8c20-cbfe00756a9e.png)

![Screen Shot 2020-10-07 at 8 36 45 AM](https://user-images.githubusercontent.com/5407441/95338363-75c6e980-0878-11eb-8a5d-545b91ff5831.png)

![Screen Shot 2020-10-07 at 8 37 01 AM](https://user-images.githubusercontent.com/5407441/95338360-7495bc80-0878-11eb-9028-a0857a7f3795.png)

![Screen Shot 2020-10-07 at 8 37 47 AM](https://user-images.githubusercontent.com/5407441/95338350-72cbf900-0878-11eb-98bd-30f53d004143.png)

**Comment by richaber** [comment]
Pinterest issues should be resolved by [WP Search with Algolia version 1.5.0](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/1.5.0).
