### ISSUE TITLE
About the operation in IE11

### ISSUE THREAD

**Issue by kusokamayarou** [WebDevStudios/wp-search-with-algolia#102]
**Describe the bug**
- In IE11, a script error was displayed.

**To Reproduce**

**Expected behavior**
- I want the page to be displayed normally in IE11 and js to work.

**Screenshots**
![ダウンロード (1)](https://user-images.githubusercontent.com/25380796/95169980-b2e69980-07ee-11eb-81b0-ce6fa1485c7e.png)

**Desktop (please complete the following information):**
 - Latest release 1.4.0

**Smartphone (please complete the following information):**
 - ???

**Additional context**

**Comment by kusokamayarou** [comment]
I turned off the Autocomplete feature.

**Comment by tw2113** [comment]
It's possible that Algolia dropped support for IE11 with their javascript bundles. We'd need to check to confirm though.

**Comment by richaber** [comment]
@daveromsey tested the autocomplete drop down in IE 11 this morning, on a site using a default Twenty* theme, and experienced no issues.

The issue described may be a conflict with some other theme/plugin/custom code.

**Comment by kusokamayarou** [comment]
@tw2113 @richaber 
Thanks.
