### ISSUE TITLE
Excluding Pages, Blog Posts in Search Results Page

### ISSUE THREAD

**Issue by AkhilAniyan** [WebDevStudios/wp-search-with-algolia#104]
Hello there!

I'm using Easy Digital Downloads and I want to search on in EDD downloads (products), EDD categories, and EDD tags.

In autocomplete settings, I selected only those three types. But on the search results page, I'm unable to only include the above three types.

Now on the search results page, pages, blog posts are also appearing with EDD products!

Any solutions?

Thanks
Akhil.

**Comment by richaber** [comment]
Howdy @AkhilAniyan 

If you want to manually control the post types for the searchable posts index, you can use the  [`algolia_searchable_post_types`](https://github.com/WebDevStudios/wp-search-with-algolia/blob/057ca7fd53c973b0e0002537b0459c3525d77aba/includes/class-algolia-plugin.php#L278) filter.

**Comment by DenisLafontTrevisan** [comment]
Hey Richard,

Could you give an example of using the filter in a child theme/functions.php?

Thanks!

**Comment by tw2113** [comment]
@DenisLafontTrevisan it's pretty much like any filter you may have used.

Looks like this one is just wanting an array of post type slugs. so something like this would suffice:

```
add_filter( 'algolia_searchable_post_types', function( $searchable_post_types ) {
    $searchable_post_types[] = 'my-custom-post-type-slug';
    $searchable_post_types[] = 'my-other-custom-post-type-slug';

    return $searchable_post_types;
} );
```
