### ISSUE TITLE
Default behavior of Yoast SEO’s noindex status and indexing via Algolia

### ISSUE THREAD

**Issue by KZeni** [WebDevStudios/wp-search-with-algolia#105]
**The problem being solved**
Yoast SEO is widely used (5+ million active installs according to WP.org as of writing), and so I'm left wondering why the setting of noindex by that plugin isn't honored by this plugin by default.

The current solution is to add something to the effect of
```
/**
 * Don't have Algolia Search index pages where the robot index
 * option in the Yoast SEO plugin is set to noindex.
 * Via: https://github.com/algolia/algoliasearch-wordpress/blob/master/docs/src/indexing-flow.md
 *
 * @param bool    $should_index
 * @param WP_Post $post
 *
 * @return bool
 */
function filter_post_for_yoast_noindex_with_algolia( $should_index, WP_Post $post ){
    if ( false === $should_index ){
        return false;
    }
    return get_post_meta($post->ID, '_yoast_wpseo_meta-robots-noindex', true) == 1 ? false : true;
}
// Hook into Algolia to manipulate the post that should be indexed.
add_filter( 'algolia_should_index_searchable_post', 'filter_post_for_yoast_noindex_with_algolia', 10, 2 );
add_filter( 'algolia_should_index_post', 'filter_post_for_yoast_noindex_with_algolia', 10, 2 );
```

to the theme's functions.php file.

However, why should this be necessary?

**The solution**
Wouldn't it make more sense if this was the default behavior of this plugin (don't serve up search results for things marked to not be indexed by search engines by the most used WordPress SEO plugin)?

At that point, sites could use a modified version of the code snippet above to include items in the Algolia search results that were set to be noindex for other search engines. Seems like this would better serve the majority of use cases while still fitting the needs of the less common use cases if/when needed (via a custom code snippet at that point.)

**Wrap up**
I'd love to see this officially adopted as part of this plugin so I'm not needing a custom code snippet on all of my sites in order to make sure something that isn't set to be indexed isn't then showing up on the site's own search results (I'm also wondering how many sites are out there where this aspect has been overlooked when it definitely shouldn't have been.)

Also, I've mentioned this at https://wordpress.org/support/topic/default-behavior-of-yoast-seos-noindex-status-and-indexing-via-algolia/ just in case others are looking for this on the WP.org forum instead of checking GitHub.

Thanks,
Kurt

**Comment by tw2113** [comment]
Chiming in with my 2 cents here. These are indexing for different, so I'm not sure why the Algolia Search plugin should rely on the Yoast setting.

I would put Algolia indexing similar to the index you see in a book. Gather up the reference shards/parts/etc and organize in an easy lookup way, for the site making use of Algolia.

Yoast indexing and noindex is meta tags that search engines and whether or not those engines should document/store/etc on their own for people searching the internet. I'll put this as equivalent to where in the bookstore a book is displayed, if at all.

If I'm doing an in-site search on a given website, I wouldn't want a plugin like Yoast dictating whether or not the individual post shows in those results

**Comment by KZeni** [comment]
@tw2113 That's where you'd have a filter available to still include noindex items in the Algolia index (a-la the reverse of how it is now.)

As an aside, what I'm proposing is actually what https://www.relevanssi.com/knowledge-base/yoast-seo-compatibility/ shows is being done for their implementation so this is far from an unusual request.

**Comment by KZeni** [comment]
> If I'm doing an in-site search on a given website, I wouldn't want a plugin like Yoast dictating whether or not the individual post shows in those results

Revisiting this topic. I do want to ask where else one would otherwise be setting whether a page is offered up via the site's Algolia search within the site admin? I think the simplest approach is to simply follow Yoast's noindex (simply says a page is not offered via any search) with it able to still index if this is disabled via a filter or setting in the plugin.

That said, maybe we don't need to change the default behavior, but it would then be nice if there was integration built into this plugin where having it honor Yoast's noindex or not is a toggle in the settings (still possibly defaulting to always index per the current behavior, but at least it then doesn't need custom code to then make it so noindex is honored by the site search as well.)

**Comment by tw2113** [comment]
I'm still personally torn on it, mostly because I still see search to find the website in general as being different from already being on the site and trying to find content within it. However, I can see benefits for it at the same time.

I would be fine with a setting to enable exclusion like this, more than making it the default behavior. Alternatively perhaps we could add a complimentary addon as its own plugin on WordPress.org.

From a support standpoint, I'd prefer to answer a "how do I do this" question than make a decision like this for the site owner where they maybe don't even realize it's happening and why.

**Comment by KZeni** [comment]
Is there an update or are there any further thoughts on this?

I'm still thinking that having this be an option would greatly simplify things (remove the need to edit theme code which is then specific to that theme's functions.php, etc.) given how widely used Yoast SEO is (could have other popular plugins be checked in a similar way [ex. All in One SEO, and possibly others.]) While that use case of setting something to noindex meaning it really shouldn't show in search of any kind (both the site's own search & external search engines) is something sites can definitely need while it could very well be the expected behavior compared to those wanting noindex content to still show in their search (might inform what the default option is for that new setting [possibly honoring it being off, in terms of having this noindex integration enabled, for existing installs so sites aren't having that behavior change while new installs can see no settings have been set and default to it being on.])

Or, would you suggest creating a plugin that has this code to help people facilitate this & determine if this integration is active or not? I don't want to create a plugin for this (probably then putting on WP.org to help streamline things further) if this is a setting that's officially adopted by this plugin at some point here, but, if this isn't going to be added anytime soon (if at all), then I could see the plugin being useful to avoid needing to add it by editing theme functions.php files individually to implement & manage this.

**Comment by tw2113** [comment]
Hi @KZeni 

I am able to say that we have things in the works internally that are going to include this type of functionality for Yoast/All In One, but also other SEO based plugins in the future.

However, I do have to emphasize that what we have in mind will not be included in the free plugin either, so a similar situation as Yoast SEO Premium, but long term our product won't be **just** SEO noindex focused.

**Comment by KZeni** [comment]
Oh? I'll be sure to wait to hear more as that does sound promising.

So it does sound like rolling out a free plugin to simplify this one particular thing might still have its place (that paid upgrade then still having its value in those other more intricate integrations & features.)

**Comment by tw2113** [comment]
If you want to, go for it. I know we're not the only Algolia Search based plugin on wordpress.org either, so there's always room https://wordpress.org/plugins/search/algolia/
