### ISSUE TITLE
Posts created before index is active don’t get deleted

### ISSUE THREAD

**Issue by richaber** [WebDevStudios/wp-search-with-algolia#107]
@ericmulder has described an issue with meta used for indexing in the WPORG support forum:
https://wordpress.org/support/topic/posts-created-before-index-is-active-dont-get-deleted/

> When you activate an index, the posts created before that get synced, but don’t receive a post_meta field called `algolia_posts_{index}_records_count`. It turns out that that meta is used to delete the post from the index. This causes orphaned posts in the algolia index which leads to confusing 404 search results. I created a video with a basic wordpress site demonstrating the issue.

There is a link to the screen recording in the support forum post for further study.

**Comment by asharirfan** [comment]
EOD Update:
I have been able to reproduce the issue on my local. Right now, I am getting myself familiar with the codebase and working on a possible solution for this problem.

**Comment by ericmulder** [comment]
The record count is set in two places (depending on the index type): https://github.com/WebDevStudios/wp-search-with-algolia/search?q=set_post_records_count

These functions are called from `update_records`  which is called from the `sync` functions (which are called from the `sync_item` function [here](https://github.com/WebDevStudios/wp-search-with-algolia/search?q=sync_item)).

The [re_index](https://github.com/WebDevStudios/wp-search-with-algolia/blob/6332237e071c40bf622f2facb38a29908a504ea0/includes/indices/class-algolia-index.php#L375) function only exists in the parent class, and doesn't call the update_records function

**Comment by ericmulder** [comment]
Thanks!
