### ISSUE TITLE
Why do we sync double indices for posts ?

### ISSUE THREAD

**Issue by lequentz** [WebDevStudios/wp-search-with-algolia#110]
Dear WebDevStudios team, 

First of all thanks for your plugin, its very useful, 

I'm using your plugin to make searchable with algolia ; posts and categories only. I'm using the auto complete feature on my home page. 

When i check on algolia, i find 3 "indices" : 
- searchable_post
- posts_post
- term_category

Why do we need to duplicate the data in different indices ? I mean i have 5K entries in searchable-posts and same in posts. It make explose my units usage ^^'. 

Thank you in advance for your reply, 

Best regards,

Quentin

**Comment by richaber** [comment]
Howdy @lequentz 

The “All Posts” (`searchable_posts`) index is used for the Instantsearch.js (“Use Algolia with Instantsearch.js”) and PHP backed search (“Use Algolia in the backend”) integrations that can be configured at WP-Admin -> Algolia Search -> Search Page.

By default, the `searchable_posts` index will include content from all post types that were registered with `exclude_from_search` set to `false`. That is to say, post types that are normally searchable in a standard WordPress install anyway (refer to [Algolia_Plugin::load_indices()](https://github.com/WebDevStudios/wp-search-with-algolia/blob/057ca7fd53c973b0e0002537b0459c3525d77aba/includes/class-algolia-plugin.php#L273-L279)). That behavior can be overridden through the use of filters to restrict the indexed post types.

The Autocomplete feature can be configured on the WP-Admin -> Algolia Search -> Autocomplete screen to use that same “All Posts” (`searchable_posts`) index, by checking the box next to “All Posts” (`searchable_posts`).

The checkboxes next to other post types on that screen are for those who wish to separate out the Autocomplete drop down results by specific post types.

If you only wish to use the `searchable_posts` index, and not have a separate `posts_post` index, check the box next to "All Posts", and uncheck the box next to "Posts".

![Screen Shot 2020-10-30 at 2 26 04 PM](https://user-images.githubusercontent.com/5407441/97748785-08dff180-1abc-11eb-88ef-a1d8d9bf159b.png)

If that solves the issue for you, and behaves the way you wish, then you can delete the additional `posts_post` index in your Algolia dashboard.

![Screen Shot 2020-10-30 at 2 30 49 PM](https://user-images.githubusercontent.com/5407441/97749630-5c9f0a80-1abd-11eb-8887-8ff35da23d2c.png)
