### ISSUE TITLE
[Feature request] Jamstack (Headless) support

### ISSUE THREAD

**Issue by hideokamoto** [WebDevStudios/wp-search-with-algolia#111]
**Is your feature request related to a problem? Please describe.**
I'll really like the plugin and Algolia, but when I renew my site as Headless WordPress, I saw this problem.

- Editor WordPress domain: api.example.com
- Public web site domain: example.com
- Algolia's indexed domain: api.example.com

Then, when we put the search form using Instansearch on my Jamstack website, the search result URL is for `api.example.com`.

But, the domain is for Editor and my WordPress site is private, so the visitor can not access the search result.

**Describe the solution you'd like**
Will you support these Headless WordPress site issues?
We hope to add the `custom domain` option into the `settings` page like this.

<img width="1098" alt="スクリーンショット 2020-11-09 17 50 16" src="https://user-images.githubusercontent.com/6883571/98520390-4fe89680-22b5-11eb-8737-a34ce970eaad.png">

When putting any parameter here, the plugin will replace the permalink or posts_url before indexing to Algolia.

**Describe alternatives you've considered**
If you have no plan to support Headless, we need to create an add-on plugin to resolve it.

```php
<?php
/**
 * @package Example_Algolia_Converter
 * @version 1.7.2
 */
/*
Plugin Name: Example Algolia domain converter
Description: Simply replace the domain
Author: Hidetaka Okamoto
Version: 0.0.1
*/

function replace_algolia_permalink_to_public_site_domain ( $url ) {
	$replaced_domain = 'public.example.com';
	$parsed_url     = wp_parse_url( $url );
	$replace_target = $parsed_url['host'];
	if ( isset( $parsed_url['port'] ) && $parsed_url['port'] ) {
		$replace_target .= ":{$parsed_url['port']}";
	}
	return preg_replace( "#{$replace_target}#i", $replaced_domain, $url );
}

function example_replace_algolia_permalink( $shared_attributes ) {
	$shared_attributes['permalink'] = replace_algolia_permalink_to_public_site_domain( $shared_attributes['permalink'] );
	return $shared_attributes;
}

function example_replace_algolia_posts_url( $user ) {
	$user['posts_url'] = replace_algolia_permalink_to_public_site_domain( $user['posts_url'] );
	return $user;
}

add_filter( 'algolia_term_record', "example_replace_algolia_permalink", 10, 1);
add_filter( 'algolia_post_shared_attributes', "example_replace_algolia_permalink", 10, 1);
add_filter( 'algolia_searchable_post_shared_attributes', "example_replace_algolia_permalink", 10, 1);
add_filter( 'algolia_user_record', "example_replace_algolia_posts_url", 10, 1);
```

**Comment by hideokamoto** [comment]
Any updates?

I made an example plugin as an extension.

https://github.com/hideokamoto/algolia-headless
ZIP: https://github.com/hideokamoto/algolia-headless/archive/v0.0.2.zip

**Comment by richaber** [comment]
When I tackle the Admin settings screens at some point, I may revisit adding this functionality directly in WPSWA.

For now, I will leave a link to @hideokamoto's own [Search with Algolia Headless extention](https://wordpress.org/plugins/search-with-algolia-headless-extention/) here.
