### ISSUE TITLE
Error pushing settings if replicas are present

### ISSUE THREAD

**Issue by yensresmann** [WebDevStudios/wp-search-with-algolia#120]
**Describe the bug**
The following error occurs when pushing index settings if there are replicas present in the config:

`RequestOptions can only be created from array or from RequestOptions object`

**To reproduce add a replica to your config and push settings:**

```php
<?php
add_filter( 'algolia_searchable_posts_index_replicas', 'my_index_replicas', 10, 2 );

function my_index_replicas(array $replicas, Algolia_Index $index) {
  $replicas[] = new Algolia_Index_Replica( 'attribute_to_sort', 'asc');
  return $replicas; 
}
?>
```

This issue can be fixed by removing the second parameter (false) of the following function call in **class-algolia-index.php**

```php
<?php
$this->get_index()->setSettings(
  array(
   'replicas' => $replica_index_names,
  ), false // this should be array() or should be removed
);
?>
```

**Comment by richaber** [comment]
Howdy @yensresmann 

@torounit was kind enough to contribute a PR to address the issue you describe.
Their PR shipped in WPSWA [version 1.7.0](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/1.7.0).

Can you verify that version 1.7.0 fixed the issue for you?
