### ISSUE TITLE
searchOnEnterKeyPressOnly fixed in 1.3.0

### ISSUE THREAD

**Issue by amrutadotorg** [WebDevStudios/wp-search-with-algolia#124]
Hi, I would like to use the `searchOnEnterKeyPressOnly` parameter.
This would require to use higher version 1.3.0 of the javascript library.

[see](https://github.com/algolia/instantsearch.js/issues/875
)

What would be the steps to check if 1.3.0 works with the current version of the plugin?

thank you

**Comment by richaber** [comment]
Howdy @amrutadotorg 

WP Search with Algolia v 1.6.0 shipped with [Instantsearch.js v 1.12.1](https://github.com/algolia/instantsearch.js/releases/tag/v1.12.1), which is newer than [Instantsearch.js v 1.3.0](https://github.com/algolia/instantsearch.js/releases/tag/v1.3.0).

**Comment by amrutadotorg** [comment]
Thank you @richaber. It works! I had a mistake in the code.
