### ISSUE TITLE
instantsearch.widgets.sortBy is not a function

### ISSUE THREAD

**Issue by amrutadotorg** [WebDevStudios/wp-search-with-algolia#133]
Hi, I'm trying to implement sorting for the results.

I followed the [documentation](https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/)

here is my code:
```
                search.addWidgets([
                                instantsearch.widgets.sortBy({
                                container: '#sort-by-container',
                        items: [
                        { value: 'wp_angolia_searchable_posts', label: 'Date Descending' },
                        { value: 'sortedByDateAsc', label: 'Date Ascending' }
                        ]
                })
                ]);
```

does the plugin support _sortBy_ _widget_?

thank you

**Comment by richaber** [comment]
Howdy @amrutadotorg 

I'm afraid the sortBy widget is not currently available in the Algolia JS libs that are bundled with WPSWA v 1.x.

We are working towards a 2.x release that will update all the bundled Algolia JS libs to their latest versions (#116 & #137).

You _could_ dequeue the Algolia JS libs that we bundle with WPSWA v 1.x, and enqueue newer versions within your child theme or a custom plugin, or wait for our upcoming 2.x release.

**Comment by richaber** [comment]
WP Search with Algolia version 2.0.0 has been tagged and released.

https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/2.0.0

https://plugins.svn.wordpress.org/wp-search-with-algolia/tags/2.0.0/
