### ISSUE TITLE
Adding custom URL field to settings

### ISSUE THREAD

**Issue by madeleinehagan** [WebDevStudios/wp-search-with-algolia#134]
Hello,

I currently use this plugin on a development site that exports the code to the live site whenever I make updates. Currently the search results on the live site always have URLs that link back to the development site.

Would it be possible to add a URL field to the settings of this plugin that can be used in place of the current default site URL, so that the URL that is pre-pended to every page in the search index can be different?

Thanks!

**Comment by richaber** [comment]
Howdy @madeleinehagan 

Although we don't _currently_ plan to implement an option for this (though we might in the future, it's just not our current focus), it can certainly be achieved with custom code.

That being said, this request sounds _similar_ to #111, and it appears that @hideokamoto has created an "add on" plugin that provides that functionality, available on WP.ORG, it might be worth giving that a look to see if it fits your needs https://wordpress.org/plugins/search-with-algolia-headless-extention/
