### ISSUE TITLE
Is this on the WevDevStudios website? Shouldn't it be?

### ISSUE THREAD

**Issue by gingersoulrecords** [WebDevStudios/wp-search-with-algolia#135]
I'd like to see a demo of this working somewhere...and I figured since WDS has a blog, it'd be a perfect opportunity to show it off. 

Anyhoo. 

DB

**Comment by richaber** [comment]
I just maintain the plugin, not the blog.  ¯\_(ツ)_/¯

We don't really have a "portfolio" of sites that have agreed to be listed here for demo purposes, but I know Yoast uses WPSWA on their website. Example: https://yoast.com/?s=algolia
