### ISSUE TITLE
Highlight in documents

### ISSUE THREAD

**Issue by amrutadotorg** [WebDevStudios/wp-search-with-algolia#136]
Hi, I was wondering if someone was able to mimic Relevanssi plugin functionality. 

In the plugin if you check the option: _Highlight in documents_, the search terms are also highlighted in the posts that are opened from the search results. Based on the feedback from the plugin author the easiest way would be to use [mark.js](https://markjs.io/) library.

**Comment by tw2113** [comment]
Not an immediate answer, but I wonder if there's already some wrapping markup getting added to the Algolia search output and terms already that could be used.

If not, then this is still a valid request in my book and will need to be looked into.

**Comment by richaber** [comment]
Howdy @amrutadotorg 

WPSWA does indeed highlight search terms in the search results. 

Example when the "Use Algolia with Instantsearch.js" option is selected:

![Screen Shot 2021-02-26 at 8 34 11 AM](https://user-images.githubusercontent.com/5407441/109313096-73583280-780d-11eb-9aba-7ac947bfc8e4.png)

Example when the "Use Algolia in the backend" option is selected:

![Screen Shot 2021-02-26 at 8 33 39 AM](https://user-images.githubusercontent.com/5407441/109313150-810db800-780d-11eb-9416-bcfa1dd48f5b.png)

**Comment by amrutadotorg** [comment]
Thank you @richaber. The idea is to highlight the terms once you open the document/link. For example Relevanssi adds at the end of the url additional parameter which looks like this _https://www.aloglia.test/linkToThePage/?highlight=spicy+jalapeno._

**Comment by tw2113** [comment]
I think this one would be better left as a 3rd party addon or similar. To get it to work, there'd need to be some way to keep track of the search phrase used previously, in order to continue highlighting on the chosen permalink.
