### ISSUE TITLE
Remove plugin's autocomplete blue cross

### ISSUE THREAD

**Issue by kaleidografik** [WebDevStudios/wp-search-with-algolia#138]
Hi guys, is it possible to remove or replace the plugins blue cross when working with autocomplete?

As it only appears when search is clicked on, finding it tricky to use the console to identify this, even if it were to hide via CSS.

Any suggestions of how to use console better to analyse the output would also be welcome.

Many thanks,
Pete

**Comment by richaber** [comment]
That is not from the plugin's styles.
That is from a user agent stylesheet.
Likely Chrome based on the screenshot.
In other words, it's your browser, not the plugin, adding that "x" to the search input.
