### ISSUE TITLE
InstantSearch is still in V1, and V4 is out

### ISSUE THREAD

**Issue by Miguelklappes** [WebDevStudios/wp-search-with-algolia#139]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a request.

**Describe the solution you'd like**
I want to stop using the Algolia PHP API client because is such a pain in the ass to use. I want to move to this plugin, however, it still functions like when it was released by Algolia 4/5 years ago.

**Describe alternatives you've considered**
The Algolia PHP API Client. I never thought that setting up WordPress with this thing would be significantly more complicated than with a Vue Stack and Firebase, or any other db.

**Additional context**
I don't want to fork the plugin and do all the updates myself, since there is already a team doing that (you guys).

**Comment by tw2113** [comment]
@richaber I believe we're working on getting this updated for version 2.0 correct?

**Comment by richaber** [comment]
We intend to update the bundled JS libs to their latest versions in a WPSWA 2.0.0 release (#116).

However, that will likely be a _breaking change_ for users that have customized the plugin's autocomplete.php and/or instantsearch.php templates in their theme.

We are preparing to communicate that to users who have customized templates _before_ we drop 2.0.0 (#137).

**Comment by Miguelklappes** [comment]
> 
> 
> We intend to update the bundled JS libs to their latest versions in a WPSWA 2.0.0 release (#116).
> 
> However, that will likely be a _breaking change_ for users that have customized the plugin's autocomplete.php and/or instantsearch.php templates in their theme.
> 
> We are preparing to communicate that to users who have customized templates _before_ we drop 2.0.0 (#137).

That's awesome! Thanks for your answer. I wanted to ask if I could get access to the plugin, As I don't have a customized template, this will not represent a problem for me.

**Comment by richaber** [comment]
@Miguelklappes If you only want to test, see the feature/instant-search-update branch.

Note that the feature branch is _not_ considered production ready, and the plugin code on that branch is not up to date with what is on main.

We've just released WPSWA 1.8.0, and will be opening a 2.0.0 branch soon to begin work on the next release.

**Comment by drjamesj** [comment]
@richaber Any update on when we might expect a 2.0 version with the relevant InstantSearch version updates released?

**Comment by richaber** [comment]
@drjamesj just as soon as I can make time for it.
If you want to have a look at what we have at the moment, the expected 2.0.0 release is on the branch [releases/2.0.0-dev](https://github.com/WebDevStudios/wp-search-with-algolia/tree/releases/2.0.0-dev).

**Comment by richaber** [comment]
WP Search with Algolia version 2.0.0 has been tagged and released.

https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/2.0.0

https://plugins.svn.wordpress.org/wp-search-with-algolia/tags/2.0.0/
