### ISSUE TITLE
Cannot connect to Algolia server with my Apllication ID

### ISSUE THREAD

**Issue by lanzoninicola** [WebDevStudios/wp-search-with-algolia#145]
**Describe the bug**
I am using a local installation of Wordpress and Woocommerce and have installed the WP Search with Algolia plugin. I followed the instructions to set up the plugin but got the following errors:
- Impossible to connect, please check your Algolia Application Id.
- We were unable to authenticate you against the Algolia servers with the provided information. Please ensure that you used a valid Application ID and Admin API key.

**To Reproduce**
1. Create an account in Algolia server
2. Go to WP Search with Algolia settings in my local environment
3. Add the Algolia's account information
4. Save changes
5. Errors are shown

**Expected behavior**
The plugin should connect to Algolia server.

**Screenshots**
These are the settings inside the wp plugin:
![image](https://user-images.githubusercontent.com/25285191/113460416-0130ca00-9419-11eb-9887-10befca69725.png)

These are the setting inside Algolia settings:
![image](https://user-images.githubusercontent.com/25285191/113460800-3d185f00-941a-11eb-86b0-84ab13f8c60e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser I tried the setup on different browser (firefox, google chrome, brave)

**Additional context**
These are my environment settings:

![wp-settings](https://user-images.githubusercontent.com/25285191/113460634-b9f70900-9419-11eb-9b8f-4cd6f5a1ec91.png)

Thanks

**Comment by tw2113** [comment]
Is this a local site or is this one that's publicly available? Trying to rule out inability to connect to external sources :D

**Comment by richaber** [comment]
Howdy @lanzoninicola, 

It appears you are using a local install on Windows? If so, this thread might be relevant to the behavior you are seeing https://github.com/WebDevStudios/wp-search-with-algolia/issues/87#issuecomment-683005495

In particular, we found that `curl.cainfo` in the [php.ini](https://www.php.net/manual/en/curl.configuration.php) needs to point to an absolute path to a Certificate Authority (CA) bundle for cURL to properly handle HTTPS communication with Algolia's APIs.

**Comment by lanzoninicola** [comment]
Thanks @richaber, I will read what you suggested. In the meantime I used XAMPP to test the integration and it works fine.  If you prefer I can close this issue.
