### ISSUE TITLE
how to index comments?

### ISSUE THREAD

**Issue by Hari-Bonda** [WebDevStudios/wp-search-with-algolia#146]
Thanks a lot for making this plugin. i have installed and updated the keys everything is working fine. but i could see any option to index wp comments .. how can i do that ? i want algolia to consider comments too ... lets say for example if user searches for "githhub" and there is no page/post exist. i want algolia to consider comments in end search results not just post/pages

is there any way to do it ? do i need to do that manually?

i have gone through the algolia wp documentation but i could not find anything related to this, your reply will be really helpful to understand and use this plugin to the core.

Thanks again for an a awesome plugin 👍

https://wordpress.org/support/topic/how-to-index-comments/

**Comment by richaber** [comment]
Howdy @Hari-Bonda,

There is no built in support to index comments, and no plans to implement that as a feature.
You would likely need to implement a custom solution to handle comments for your specific use case.

**Comment by smithjohnau** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/LENOVO/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/LENOVO/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



<a   href=https://www.helloassignmenthelpau.com/university-assignment-help.html>https://www.helloassignmenthelpau.com/university-assignment-help.html</a>
--
<a   href=https://www.helloassignmenthelpau.com/economics-assignment-help.html>https://www.helloassignmenthelpau.com/economics-assignment-help.html</a>
<a   href=https://www.helloassignmenthelpau.com/assignment-help-adelaide.html>https://www.helloassignmenthelpau.com/assignment-help-adelaide.html</a>
<a   href=https://www.helloassignmenthelpau.com/assignment-help-sydney.html>https://www.helloassignmenthelpau.com/assignment-help-sydney.html</a>
<a   href=https://www.helloassignmenthelpau.com/java-assignment-help.html>https://www.helloassignmenthelpau.com/java-assignment-help.html</a>
<a   href=https://www.helloassignmenthelpau.com/chcdiv001-case-study-answers.html>https://www.helloassignmenthelpau.com/chcdiv001-case-study-answers.html</a>
<a   href=https://www.helloassignmenthelpau.com/diploma-courses/chcece019-assessment-answers.html>https://www.helloassignmenthelpau.com/diploma-courses/chcece019-assessment-answers.html</a>
<a   href=https://www.helloassignmenthelpau.com/finance-assignment-help.html>https://www.helloassignmenthelpau.com/finance-assignment-help.html</a>
<a   href=https://www.helloassignmenthelpau.com/management-assignment-help.html>https://www.helloassignmenthelpau.com/management-assignment-help.html</a>
<a   href=https://www.helloassignmenthelpau.com/project-management-assignment-help.html>https://www.helloassignmenthelpau.com/project-management-assignment-help.html</a>



</body>

</html>
