### ISSUE TITLE
Use the Visual Editor with Category Pages

### ISSUE THREAD

**Issue by gbvaz** [WebDevStudios/wp-search-with-algolia#152]
Hi, this is more of a question than a bug report or feature request, because I don't know if it's implemented or not.

I came across this article in Algolia docs, and I was wondering why isn't it working:
https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/how-to-configure-and-use-the-visual-editor-with-category-pages/#getting-started

What I'm trying to do is have Algolia dictate the sorting order in Product Category pages in WP using their visual editor.

Here's an example:
![image](https://user-images.githubusercontent.com/7118638/118307743-7b954500-b4c1-11eb-9ce4-2c5f12379e51.png)

The problem is that the same category in my WP install is not following the sorting order I created in Algolia:
![image](https://user-images.githubusercontent.com/7118638/118307927-ba2aff80-b4c1-11eb-9aac-fb87676b69f5.png)

Is this really a bug, or is it just not implemented, can you put me in the right direction here on how could I make it work?

Kind regards

**Comment by tw2113** [comment]
We're not sure exactly what type of feature this would be, from what I'm being told, so it's very possible a custom implementation going on here. Definitely not part of the plugin that we forked and are maintaining.

**Comment by gbvaz** [comment]
This would be for product merchandising sorting, it would replace a need for a plugin like this for example: https://woocommerce.com/pt-br/products/product-merchandizing/ as it would take over the default sorting option for each product category page, and would apply the rules we created in Algolia, does that make sense? In general terms, what would be the necessary changes in the plugin in order to achieve such thing?

**Comment by tw2113** [comment]
Unless I'm mistaken, I believe Algolia Search and that Product Merchandizing plugin are entirely different in terms of intent and functionality. Algolia isn't about how the results are displayed, it's about as fast as possible results for given user queries. That plugin looks more like customization of sorting, priority, and granular ordering.

**Comment by gbvaz** [comment]
Exactly, you are correct and I know this is different from the main reason why one would use Algolia + WP Search, but it's indeed a feature provided by Algolia (https://www.algolia.com/doc/guides/managing-results/rules/merchandising-and-promoting/how-to/how-to-configure-and-use-the-visual-editor-with-category-pages/) and would be an additional feature very useful for e-commerce stores with any kind of merchandising needs, featuring products in category pages, making products fit more nicely next to each other and so on, instead of having to rely on the either the default sorting options from Woocommerce or any other plugin or custom function.

I'm coming from Elasticsearch + Elasticpress, which is kind of similar to using Algolia + WP Search, and one of the main differences I'm seeing is that Elasticpress "translates" or replaces all main WP queries into Elasticsearch queries, so all WP pages are being covered in a way whereas, right now, Alogia + WP Search only covers the search functionality, if I'm not mistaken, correct?

**Comment by richaber** [comment]
> would be an additional feature very useful for e-commerce stores

WP Search with Algolia (WPSWA) does not provide any specific support for any e-commerce plugin.

> Elasticpress "translates" or replaces all main WP queries into Elasticsearch queries

WPSWA only effects one WP_Query, the WP_Query that fires on search, but only if "Use Algolia in the backend" is selected under WP-Admin → Algolia Search → Search Page.

There are no plans to overtake sorting/ordering of any other WP Queries.

>  right now, Alogia + WP Search only covers the search functionality, if I'm not mistaken, correct?

Correct. WPSWA is solely focused on indexing and searching.
