### ISSUE TITLE
All WooCommerce products indexed with content: "Content Area"

### ISSUE THREAD

**Issue by isvaljek** [WebDevStudios/wp-search-with-algolia#153]
All of the WooCommerce products are indexed with the JSON field "content" equaling "Content Area".
Other fields seem to index properly with the latest WP/WC/WP Search with Algolia combo.

![image](https://user-images.githubusercontent.com/2500267/118403130-3f9ee300-b66d-11eb-8a57-370c04dbd070.png)

**Comment by tw2113** [comment]
For what it's worth, we have zero official integration with WooCommerce, if I recall correctly, and don't have any present plans to. Sounds like there's something at your config level that may need to be revised/re-mapped?

**Comment by richaber** [comment]
This looks like an issue with a customization, a theme, or another plugin, and not specifically an issue with WPSWA.
