### ISSUE TITLE
queryRuleCustomData widget is not a function

### ISSUE THREAD

**Issue by AramCP** [WebDevStudios/wp-search-with-algolia#154]
**Describe the bug**

I was trying to add the [queryRuleCustomData](https://www.algolia.com/doc/api-reference/widgets/query-rule-custom-data/js/) widget to display a banner above the results. But it didn't work as it tells me it's not a function.
What I have done is to go to the instantsearch.js file where all the widgets are, and indeed this widget and quite a few others are not present.

![image](https://user-images.githubusercontent.com/23645215/119221333-21166d00-baef-11eb-8d68-5bd34c7866fe.png)

My question is if there is any other way to display this widget, thanks.

**Comment by richaber** [comment]
Howdy @AramCP,

I'm afraid the queryRuleCustomData widget is not currently available in the Algolia JS libs that are bundled with WPSWA v 1.x.

We are working towards a 2.x release that will update all the bundled Algolia JS libs to their latest versions (#116 & #137).

You could dequeue the Algolia JS libs that we bundle with WPSWA v 1.x, and enqueue newer versions within your child theme or a custom plugin, or wait for our upcoming 2.x release.

**Comment by richaber** [comment]
WP Search with Algolia version 2.0.0 has been tagged and released.

https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/2.0.0

https://plugins.svn.wordpress.org/wp-search-with-algolia/tags/2.0.0/
