### ISSUE TITLE
Vanilla JavaScript Version

### ISSUE THREAD

**Issue by asha23** [WebDevStudios/wp-search-with-algolia#156]
**Is your feature request related to a problem? Please describe.**
It would be great to have a vanilla JavaScript version of this plugin. I tend to steer clear of JQuery for most projects these days as I feel it adds unnecessary bloat to the code

**Describe the solution you'd like**
Just a vanilla JS option :)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by richaber** [comment]
You could copy the two template files to your child theme and customize the JS in those template files so it does not use jQuery.

**Comment by peiche** [comment]
Just chiming in... WordPress does and will (at least in the immediate future) include jQuery, unless you've taken extra steps to disable it. That said, I have custom templates in my theme for which I rewrote much of the jQuery into plain ol' JS. So... I know exactly where you're coming from. :)

**Comment by asha23** [comment]
Yeah I always turn off any JQuery on WP sites.

Not to worry. I have written my own Vanilla JS to deal with the search.
