### ISSUE TITLE
Can be used alognside Bogo trasnslate plugin?

### ISSUE THREAD

**Issue by tomasts248** [WebDevStudios/wp-search-with-algolia#158]
The idea is to have content in english and spanish by using Bogo translate plugin link here:
https://wordpress.org/plugins/bogo/

So the question is:; is possible to use spanish search results for spanish page and english results for the english page version of the same page?

**Comment by richaber** [comment]
@tomasts248 I'm not familiar enough with Bogo to provide any direction on how to integrate with it.
I can say that users have successfully integrated with [WPML](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/WPML) and [Polylang](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Polylang), which you can find some details of in the [Wiki](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/) under Integrations.
They might provide some information that could potentially be useful for integrating with Bogo.

**Comment by tomasts248** [comment]
Thank you!  can I try it in a local test installation and report back? Sorry for the late answer..
Regards

**Comment by richaber** [comment]
@tomasts248, sure, if you figure out how to make that work, sharing how you did it could benefit others looking to achieve the same.
