### ISSUE TITLE
How can I add multiple no-result sections

### ISSUE THREAD

**Issue by sarfarazansari** [WebDevStudios/wp-search-with-algolia#159]
**Is your feature request related to a problem? Please describe.**
Am actually developing an application in which it will search on three sources (index) at a time.
and the UI looks like something attached image.
so am looking for a way to display separate messages for each datasets.

![image](https://user-images.githubusercontent.com/3416989/123081136-445c7100-d43b-11eb-8c91-f45264d84e53.png)

It would be great if you have already something like this.
otherwise I am glad if you guys guide me how to achieve.

thanks

![image](https://user-images.githubusercontent.com/3416989/123081365-7ff73b00-d43b-11eb-92c9-4b0b19015070.png)

I would like to have this no-result section to be section wise for each datasets

**Comment by richaber** [comment]
Howdy @sarfarazansari 

WP Search with Algolia does not provide a feature like what you describe.

That sounds like it requires custom JavaScript development, and I cannot provide direction on how to achieve what you describe.

It might be best to use WP Search with Algolia only for it's indexing capabilities, and then build your own frontend application using Algolia's JS libraries (they have newer versions with more capabilities than what is currently bundled with WPSWA).

Algolia's documentation might be a good place to start, here's a link to their ["Building Search UI" documentation](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/).
