### ISSUE TITLE
Only Show in Stock Products

### ISSUE THREAD

**Issue by mehboobposhaprani** [WebDevStudios/wp-search-with-algolia#16]
Hey,

I know this could be an easy fix, but I was not able to get to a solution. Is it possible to only display in stock products in autocomplete.

 "facetFilters": [
  [
   "taxonomies.product_visibility:outofstock"
  ]
 ]

Please a detailed step would be really appriciated.

Either do not display out of stock product, or display in stock products 1st, any one of the solution will work for me.

Thanks in advance.

**Comment by richaber** [comment]
Closing this issue as WP Search with Algolia (WPSWA) does not provide any specific support for any e-commerce plugin, and we are unable to provide support for customization requests here.
