### ISSUE TITLE
How to add further indexes to autocomplete

### ISSUE THREAD

**Issue by XpertdUK** [WebDevStudios/wp-search-with-algolia#162]
Hi, I am new to this and heard great things about the plugin. I wanted to ask for a little support. I have a community website - https://development.xpertd.com/v2 which has a member directory using buddypress and youzify however I want to be able to search the entire member profile for information but not sure how to index those necessary pages. Are you able to shed some light on how to do this?

**Comment by richaber** [comment]
Howdy @XpertdUK 

I am not terribly familiar with BuddyPress, and I have no familiarity with Youzify.
Is the "member profile" a WP_Post object?
Is the data you're looking to index stored in "meta"?
