### ISSUE TITLE
Error when entering credentials

### ISSUE THREAD

**Issue by asha23** [WebDevStudios/wp-search-with-algolia#167]
**Describe the bug**

Fatal error: Uncaught Error: Class 'Algolia\AlgoliaSearch\Http\CurlHttpClient' not found in /var/www/corp-cloudflare.*******..com/wp-content/plugins/wp-search-with-algolia/includes/factories/class-algolia-http-client-interface-factory.php:117 Stack trace: #0 /var/www/corp-cloudflare.*******.com/wp-content/plugins/wp-search-with-algolia/includes/factories/class-algolia-http-client-interface-factory.php(44): Algolia_Http_Client_Interface_Factory::create_http_client() #1 /var/www/corp-cloudflare.*******..com/wp-content/plugins/wp-search-with-algolia/includes/factories/class-algolia-search-client-factory.php(55): Algolia_Http_Client_Interface_Factory::create() #2 /var/www/corp-cloudflare.*******.com/wp-content/plugins/wp-search-with-algolia/includes/class-algolia-api.php(124): Algolia_Search_Client_Factory::create('ZTOITHRBV2', '7aab3b478363ffc...') #3 /var/www/corp-cloudflare.*******..com/wp-content/plugins/wp-search-with-algolia/includes/admin/class-algolia-admin-page-settings.php(371): Algolia_API::assert_ in /var/www/corp-cloudflare.*******..com/wp-content/plugins/wp-search-with-algolia/includes/factories/class-algolia-http-client-interface-factory.php on line 117

**To Reproduce**
1. Algolia plugin in the backend
2. Enter credentials
3. Click on "Save Changes"

**Expected behavior**

Expected the plugin to update and enter my credentials

 - OSX
 - Chrome
 - Latest
 
 Latest version of the Algoiia plugin.. 
 
 Any ideas?

**Comment by richaber** [comment]
Howdy @asha23,
If you have access to the filesystem where this is installed, via (S)FTP, SSH, etc., Can you verify that this file exists? [wp-search-with-algolia/includes/libraries/algoliasearch-client-php/src/Http/CurlHttpClient.php](https://github.com/WebDevStudios/wp-search-with-algolia/blob/2.0.1/includes/libraries/algoliasearch-client-php/src/Http/CurlHttpClient.php)

**Comment by asha23** [comment]
Hi this is resolved, sorry - I was behind a VPN so guess this is why it wasn't picking up.
