### ISSUE TITLE
Search Form facet selections do not affect URL

### ISSUE THREAD

**Issue by fyaconiello** [WebDevStudios/wp-search-with-algolia#170]
**Is your feature request related to a problem? Please describe.**
I want to be able to search/narrow a results page and share the link that maintains the search/filter choice selections. Currently the search terms do not update the url params for the page. This makes it so that back/forward buttons don't work, faceted queries cannot be shared, etc.

**Describe the solution you'd like**
I would like better support for search form URL parameter mapping and browser history support.

**Describe alternatives you've considered**
I've looked into how instantsearch works and it appears that there is a feature that should support this. However it is not clear how to implement it with this plugin without overriding some important plugin files.

https://community.algolia.com/instantsearch.js/v2/instantsearch.html#struct-InstantSearchOptions-urlSync
https://github.com/algolia/instantsearch.js/pull/2829

**Additional context**
I think the problem is self explanatory but let me know if I can provide more information.

Edit:

![filtered result](https://user-images.githubusercontent.com/227515/129408543-87915bb7-a4f3-467c-bdaf-0dc90aff40c0.png)

In this image I've selecte categories and am on the last page of results - none of that is reflected in the url params.

**Comment by richaber** [comment]
Howdy @fyaconiello,

If you have a look at [templates/instantsearch.php](https://github.com/WebDevStudios/wp-search-with-algolia/blob/2.0.1/templates/instantsearch.php#L81-L103) you will see that we do implement `routing`, but our out-of-the-box `stateMapping` implementation only maps input queries and pagination at the moment.

If you wanted to extend it to also handle, for example, tags, categories, and authors, that is absolutely possible. You would want to refer to the instantsearch.js documentation regarding `routing` and `stateMapping`. This is a good place to look https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/#rewriting-urls-manually

>. InstantSearch manages a state called `uiState`. It contains information like query, facets, or the current page, including the hierarchy of the added widgets.
> 
> To persist this state in the URL, InstantSearch first converts the `uiState` into an object called `routeState`. This `routeState` then becomes a URL. Conversely, when InstantSearch reads the URL and applies it to the search, it converts `routeState` into `uiState`. This logic lives in two functions:
> 
> `stateToRoute`: converts `uiState` to `routeState`.
> `routeToState`: converts `routeState` to `uiState`.

To customize the templates that ship with the plugin, copy the `templates` directory from the plugin into your child theme, rename the directory to `algolia`, and then customize the `stateToRoute` and `routeToState` functions.

This is an _oversimplified_ example of how you could add tags (`refinementList`), categories (`hierarchicalMenu`), and authors (`menu`) to the `stateMapping`....
```
/* Instantiate instantsearch.js */
var search = instantsearch({
	indexName: algolia.indices.searchable_posts.name,
	searchClient: algoliasearch( algolia.application_id, algolia.search_api_key ),
	routing: {
		router: instantsearch.routers.history({ writeDelay: 1000 }),
		stateMapping: {
			stateToRoute( indexUiState ) {
				const routeState = {
					s: indexUiState[ algolia.indices.searchable_posts.name ].query,
					page: indexUiState[ algolia.indices.searchable_posts.name ].page,
					refinementList: indexUiState[ algolia.indices.searchable_posts.name ].refinementList,
					hierarchicalMenu: indexUiState[ algolia.indices.searchable_posts.name ].hierarchicalMenu,
					menu: indexUiState[ algolia.indices.searchable_posts.name ].menu
				};
				return routeState;
			},
			routeToState( routeState ) {
				const indexUiState = {};
				indexUiState[ algolia.indices.searchable_posts.name ] = {
					query: routeState.s,
					page: routeState.page,
					refinementList: routeState.refinementList,
					hierarchicalMenu: routeState.hierarchicalMenu,
					menu: routeState.menu
				};
				return indexUiState;
			}
		}
	}
});
```

I can't really provide support for customizations, but between the above example, and reading the Algolia Instantsearch.js docs on `routing` and `stateMapping`, you should be able to achieve your goal.

**Comment by fyaconiello** [comment]
We hadn't updated our plugin install since creating this algolia demo branch, and its been hanging out a bit on our side. So thats likely why I didn't see the newer router work

![Screenshot-20210814133540-1680x750](https://user-images.githubusercontent.com/227515/129455659-764d9446-30e8-48e5-ad7b-f75792fc69f1.png)

In order to not break updates, is there a preferred way of making overrides to this template/JS? 

hooks vs standard template hierarchy?

**Comment by tw2113** [comment]
I believe the method to override is the same, it's just that the content in the new templates are vastly different than they were previously, so you definitely need to update to match
