### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Algolia_Admin' not found in class-algolia-plugin.php:168

### ISSUE THREAD

**Issue by goodbrotherkitchens** [WebDevStudios/wp-search-with-algolia#183]
I am receiving these errors for the last few days and didn't able to track down how can I resolve them.

Can you guys please have a look into the errors and let me know can I resolve them.

PS: WordPress, woocommerce and plugin is updated

```
Stack trace:
#0 /home/---/public_html/wp-includes/class-wp-hook.php(303): Algolia_Plugin->load('')
#1 /home/---/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#2 /home/---/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /home/---/public_html/wp-settings.php(578): do_action('init')
#4 /home/---/public_html/wp-config.php(75): require_once('/home/wwwmcds/p...')
#5 /home/---/public_html/wp-load.php(50): require_once('/home/wwwmcds/p...')
#6 /home/---/public_html/wp-cron.php(44): require_once('/home/wwwmcds/p...')
#7 {main}
  thrown in /home/---/public_html/wp-content/plugins/wp-search-with-algolia/includes/class-algolia-plugin.php on line 168
```

**Comment by richaber** [comment]
Howdy @goodbrotherkitchens,

Can you verify that the `Algolia_Admin` class file exists at `wp-search-with-algolia/includes/admin/class-algolia-admin.php`?

**Comment by tw2113** [comment]
Not sure if a case of you simply didn't paste it all, or you have a partial file downloaded, but the class file should be 288 lines long https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/admin/class-algolia-admin.php

If just a partial paste, ignore this part.

**Comment by tw2113** [comment]
Closing as invalid at the moment. I haven't seen anyone else chime in with similar issues, so I suspect it was a momentary issue.
