### ISSUE TITLE
Autocomplete field is not syncing to the search result

### ISSUE THREAD

**Issue by Wayne-Pastoral** [WebDevStudios/wp-search-with-algolia#185]
We're basically needing to convert Algolia from the old version to the new version and fix the bugs.
Search is providing instant results but not providing predictions on what to search.
we customized autocomplete.php and instantsearch.php templates,  two templates are breaking when we update the plugin.
the version is 1.8.0 we need to update to the latest version.

**Comment by tw2113** [comment]
My first question is how do things look when allowing the default template files get used? are all the parts you're expecting to see working, like the predictions etc?

I know version 2.0.0 was a pretty large overhaul of the plugin that is necessitating updating customized templates. So it's possible you may need to back up your current templates, then move new overrides into place and re-customize as needed afterwards. A bit of a pain we know, but a number of libraries in use got big updates.
