### ISSUE TITLE
indexing buddypress groups

### ISSUE THREAD

**Issue by cezarneaga** [WebDevStudios/wp-search-with-algolia#187]
**Is your feature request related to a problem? Please describe.**
the plugin indexes gpages post type and the permalink is wrong. ?post_type=gpages&p=455415 will not resolve to /groups/group-name

**Describe the solution you'd like**
algolia index should contain the group nice url

**Describe alternatives you've considered**

**Additional context**
the old plugin used to work.

**Comment by cezarneaga** [comment]
is this closed because groups are now indexed?

**Comment by tw2113** [comment]
Doesn't look like any changes were made around BuddyPress/BuddyPress groups. This one is looking like it's going to have to be a custom solution, and not something that's going to be added into the core plugin, thus why it got closed.
