### ISSUE TITLE
[housekeeping] Get release ready for 1.1

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wp-search-with-algolia#19]
- [x] Translations
- [x] Add @richaber to list of contributors 
- [x] Update minimum version of WordPress to 5.3
- [x] Update minimum version of PHP to match WordPress core (7.2)

**Comment by richaber** [comment]
WP Search with Algolia version 1.1.0 tagged and released.
Available in this project's releases under the [1.1.0 tag](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/1.1.0).
Available for download at [WordPress.org](https://wordpress.org/plugins/wp-search-with-algolia/).
