### ISSUE TITLE
autocomplete not returning results

### ISSUE THREAD

**Issue by seanvandermolen** [WebDevStudios/wp-search-with-algolia#194]
**Describe the bug**
Autocomplete is not returning results

**To Reproduce**
1. Go to 'dealersupply.com'
2. Use search, no results, hit enter and normal results work

**Additional context**
Disabled all plugins besides core WC and the issue persists
Search works in the algoria dashboard

**Comment by seanvandermolen** [comment]
> Thank you for contacting the Algolia team.
> I have checked the website (dealersupply.com) and confirmed that the search results are not shown when I input query to the search box.
> On the other hand, I also confirmed that the website receives a response from the Algolia search API for the query in the network communication.
> That said, it looks the issue is the way the frontend renders hits after receiving search results.

**Comment by richaber** [comment]
Howdy @seanvandermolen,

We do not offer any specific WooCommerce integration.

However, it appears you have managed to get your custom integration working.

![Screen Shot 2021-12-03 at 4 14 38 PM](https://user-images.githubusercontent.com/5407441/144679994-32c0f03f-6a34-4786-a5fc-45ae684bb599.png)
