### ISSUE TITLE
Adjust number input padding on autocomplete page.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#195]
We're kind of cramped in the number input field, both in chrome and firefox, and probably other browsers too. I have attached screenshots of Chrome on top and Firefox on bottom, showing current status of the padding, and then also with the 8px padding removed.

Current:
<img width="112" alt="current" src="https://user-images.githubusercontent.com/484075/146435877-863bad4a-31f6-4de0-a9d4-a117c2c0a4a6.png">

Removed padding:
<img width="128" alt="no-padding" src="https://user-images.githubusercontent.com/484075/146435880-d1bf56bf-585d-4c8f-8e00-6c06add68b64.png">

Padding is coming from WP core stylesheets from the looks of things.

**Comment by richaber** [comment]
It appears the input has a hardcoded inline style width of 40px in [includes/admin/partials/page-autocomplete-config.php](https://github.com/WebDevStudios/wp-search-with-algolia/blob/57716727e6fb5047c7b07be28dfe927bad8341c4/includes/admin/partials/page-autocomplete-config.php#L50)
```
<input style="width: 40px; text-align: center;" type="number" name="algolia_autocomplete_config[<?php echo esc_attr( $index['index_id'] ); ?>][max_suggestions]"  value="<?php echo (int) $index['max_suggestions']; ?>" />
```

What would be a preferable width?

**Comment by tw2113** [comment]
Based on my comments above and just memory, overriding the padding to be zero would result in the last screenshot, which i think is sufficient. It's not so much the width that's the issue, but pushing things inside around a bit.

Alternatively, if you'd prefer to just adjust the inline style there, increasing by 16px should get roughly the same result, for 2 sides of 8px each.
