### ISSUE TITLE
Example of excluded_from_search => true but still auto-index?

### ISSUE THREAD

**Issue by mfs-nebo** [WebDevStudios/wp-search-with-algolia#196]
We have a CPT that we're using for content that's presented in a grid and manipulated by the users with Alogolia facets (and perhaps Search of that index). But that CPT's content is not to be included in site search results.

Ultimately, we'd like to maintain auto-index'ing of the CPT (because telling the client to manually update the CPT index is likely to be hit or miss).

Perhaps you have such an example? Or at least some insights on how to approach it? My sense is, it's definitely possble. But I figured it's best to ask the always helpful WDS before getting sucked down the rabbit hole :)  TIA

**Comment by tw2113** [comment]
Closest I can think of and see quickly offhand is this snippet below from `includes/class-algolia-plugin.php` and the `load_indices()` method.

```
// Add a searchable posts index.
$searchable_post_types = get_post_types(
	array(
		'exclude_from_search' => false,
	),
	'names'
);
$searchable_post_types = (array) apply_filters( 'algolia_searchable_post_types', $searchable_post_types );
```

Basically use the filter to re-include the post types in question.

**Comment by mfs-nebo** [comment]
Great. Thanks @tw2113 . I'll give that a spin. Happy New Year. 

p.s. Given GDPR and similar, I think it would be wise for the default for the Users table and Users meta table not to be indexed and sent to Algolia. That is, you'd have to set up a filter to have them intentionally indexed + sent to Algolia. Maybe?

**Comment by tw2113** [comment]
Out of box, I don't think we do that much collection of data, especially personally identifiable details.

https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/indices/class-algolia-users-index.php#L70-L100

I'm seeing biography, avatar, author archive url, display name, total post count.

What besides those are you potentially seeing get indexed with your own install?
