### ISSUE TITLE
No obviously shown "position" column on Autocomplete setting page

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#197]
"Use the `Position` column to reflect the order of the sections in the dropdown menu." is listed at the bottom to try and help the user. However, we don't mention "Position" in any of the headings to help confirm which should be getting looked at.

Pretty sure it's the first one, but helps to be explicit.

**Comment by richaber** [comment]
Positioning on Autocomplete Configuration is drag-and-drop. 

That message appears to be outdated, a leftover from a point in the original plugin's development, when the Position column was removed and replaced with jQuery UI Sortable, in this commit [453f26e1](https://github.com/algolia/algoliasearch-wordpress/commit/453f26e1f37d6e19d4c3bc608bb5b8ef2dd0b6e1#diff-3568e22a445d2ae758d175f987e1e8f8113d0de75e264753146c11eb94f4a859)

**Comment by richaber** [comment]
How about replacing that Position wording with something like ....
> Use drag and drop to control the order of the sections in the autocomplete dropdown menu.

**Comment by tw2113** [comment]
that'd work just as well. whatever helps keep things clear on how to interact
