### ISSUE TITLE
Moving automcomplete html span markup

### ISSUE THREAD

**Issue by eSaner** [WebDevStudios/wp-search-with-algolia#198]
Is it possible to move where the autocomplete html span markup is inserted? It would be helpful for me to move it inside a container element of a fullscreen popup search modal.

Thanks.

**Comment by tw2113** [comment]
I would check out https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Customize-Templates which documents how to customize the templates to your hearts desire. I know I've done plenty of template customization in the past month or two, and it's all very flexible.

**Comment by eSaner** [comment]
Thought there might be a hook, but I ended up just using js after the span has loaded.
