### ISSUE TITLE
Issue with logging

### ISSUE THREAD

**Issue by fabswt** [WebDevStudios/wp-search-with-algolia#201]
**Describe the bug**

When saving the settings, getting this:

> Fatal error: Declaration of Algolia\AlgoliaSearch\Log\DebugLogger::log($level, $message, array $context = []) must be compatible with Psr\Log\AbstractLogger::log($level, Stringable|string $message, array $context = []): void in /var/www/html/bilingueanglais/web/blog/plugins/wp-search-with-algolia/includes/libraries/algoliasearch-client-php/src/Log/DebugLogger.php on line 41
> There has been a critical error on this website. Please check your site admin email inbox for instructions.

**To Reproduce**

I'm using:
- PHP Version 8.1.3
- wp-search-with-algolia 2.1.0 (latest) which itself uses algoliasearch-client-php 3.1.0
- Just go to the settings for the plugin and try to save.

**Fix**

In wp-search-with-algolia/includes/libraries/algoliasearch-client-php/src/Log/DebugLogger.php, replaced this:

```
public function log($level, $message, array $context = [])
```

With this:

```
public function log($level, $message, array $context = []): void
```

as is the case in algoliasearch-client-php 3.2.0 which came out in January (see https://github.com/algolia/algoliasearch-client-php/blob/master/src/Log/DebugLogger.php).

**Comment by tw2113** [comment]
Hi @fabswt

Thanks for this. Definitely something we'll need to get updated and possibly upgrade our bundled version of the algoliasearch-client-php library as a whole. I know I see `^3.0.2` in our composer file for version restraints.

**Comment by fabswt** [comment]
It's worth pointing that this makes it impossible to configure the plugin in production via the Settings pane.

Had to do it by hand inside the database: in `wp_settings`, look for `algolia_api_key` and set the value (that's `Admin API Key` in the *API Keys* details in the Algolia dashboard.)

**Comment by fabswt** [comment]
Any ETA on the plugin update?

**Comment by tw2113** [comment]
We don't have any exact release date planned for this just yet as we do need to make sure that the library update doesn't break other functionality and whatnot for our other existing users.

We also haven't seen many people yet on PHP 8.1 already, so that's a factor as well here. We need to make sure we're not updating the shipped packages to a version that eliminates some of the PHP versions we still want to support. That said, we would love it if you could help test and confirm things work fine with your own install

**Comment by fabswt** [comment]
> we would love it if you could help test and confirm things work fine with your own install

Locally, I was able to push blogposts to an index on Algolia, and use that index to perform search using an autocomplete search widget. In other words: worked fine for all I could see. 

# Hotfix

I really need this to work, so I created a hotfix for my own needs. FYI:

```markdown

# Why a hotfix

See https://github.com/WebDevStudios/wp-search-with-algolia/issues/201

In short:

- wp-search-with-algolia 2.1.0 (latest) uses algoliasearch-client-php 3.1.0
  which does NOT work with PHP 8.1, producing this fatal error:

> Fatal error: Declaration of Algolia\AlgoliaSearch\Log\DebugLogger::log($level, $message, array $context = []) must be compatible with Psr\Log\AbstractLogger::log($level, Stringable|string $message, array $context = []): void in /var/www/html/bilingueanglais/web/blog/plugins/wp-search-with-algolia/includes/libraries/algoliasearch-client-php/src/Log/DebugLogger.php on line 41
There has been a critical error on this website. Please check your site admin email inbox for instructions.

My hotfix:

- Updated the dependencies manually:
  - Renamed plugins/wp-search-with-algolia to plugins/wp-search-with-algolia-hotfix
  - In it, deleted includes/libraries/algoliasearch-client-php (3.1.0)
  - Pasted includes/libraries/algoliasearch-client-php (3.2.0)
    - from https://github.com/algolia/algoliasearch-client-php
- Stopped using wpackagist to deploy the plugin, opting instead for a manual deploy:
  - Removed wpackagist-plugin/wp-search-with-algolia
  - Updated my .gitignore with `!/web/blog/plugins/wp-search-with-algolia-hotfix`
- Enabled the plugin locally:
  - Enabled it https://bilingueanglais.localhost/wp-core/wp-admin/plugins.php
  - Checked it worked https://bilingueanglais.localhost/wp-core/wp-admin/admin.php?page=algolia
  - Tested saving works fine -- it does.
- Deployed
  - Commit, push.
- Enabled the plugin in production:
  - Enabled it https://bilingueanglais.com/wp-core/wp-admin/plugins.php
  - Checked it worked https://bilingueanglais.com/wp-core/wp-admin/admin.php?page=algolia
  - Tested saving works fine -- it does.
  - Enabled Autocomplete + indexed `searchable_posts`.
- Test my autocomplete search widget:
  - Works fine. (Showing results, which work fine.)


# Memo

Once wp-search-with-algolia gets officially updated with support for
algoliasearch-client-php 3.2.0 or higher, I'll want to deactivate my own plugin
then get back to using wpackagist to install it:

    composer require wpackagist-plugin/wp-search-with-algolia
```

**Comment by tw2113** [comment]
Noted on the need to hotfix and get it working for yourself, by every means.

I am not suspecting a lot of issues, but we still need to do our due diligence which I know you're understanding as well.

The library still says they support PHP 7.2+ which aligns with our current plugin PHP support.

Hopefully we can get this handled asap.

**Comment by jgmdigital** [comment]
@tw2113 @fabswt 

For anyone working with PHP 8.1, we have created a temporary patch:

```bash
diff --git a/includes/libraries/algoliasearch-client-php/src/Log/DebugLogger.php b/includes/libraries/algoliasearch-client-php/src/Log/DebugLogger.php
index 0c76540..be2981f 100644
--- a/includes/libraries/algoliasearch-client-php/src/Log/DebugLogger.php
+++ b/includes/libraries/algoliasearch-client-php/src/Log/DebugLogger.php
@@ -38,7 +38,7 @@ final class DebugLogger extends AbstractLogger
     /**
      * {@inheritdoc}
      */
-    public function log($level, $message, array $context = [])
+    public function log($level, $message, array $context = []): void
     {
         if (self::$isEnabled) {
             $logMessage = [

```

We have used https://github.com/cweagans/composer-patches to install the above patch.

It would be good to see this included in a future release of the plugin, to avoid breaking old versions you would need to update the PHP requirement in the composer.json to prevent this installing on clients running older versions of PHP; I would create a fork but I'd imagine there are other parts of the code that may need updating also and so I wouldn't want to suggest only the above change without a full code review.

Any questions, please let me know.
