### ISSUE TITLE
Search is not auto-filling search bar

### ISSUE THREAD

**Issue by marcperel** [WebDevStudios/wp-search-with-algolia#206]
**Describe the bug**

**To Reproduce**
1. Go to our test site: [Inside Guide](https://dev.signposthq.co.za/insideguide/)
2. Search for anything and press enter to submit the form
3. Scroll down to the search results
4. See that the search term is not automatically filled in
5. That means that the search form isn't actually showing what we searched for (we think this is due to point 6, repeating scripts)
6. Additionally, if you look at the source of the site you'll see that the footer seems to be repeating itself (this isn't the case without the plugin active) because you'll see two `</html>` tags displaying

**Expected behavior**
We expect that the search query to populate the results page and display the correct results.

**Screenshots**

![image](https://user-images.githubusercontent.com/3140054/161075359-f794db92-fe83-413d-8f85-4698874e35fb.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome, Safari and Firefox
 - All versions

**Additional context**
We are so grateful for this plugin, thank you!

**Comment by marcperel** [comment]
@tw2113 no we haven't, but maybe because we're using a custom theme, we should copy the template into our theme, in case it's being loaded twice via a hook?

**Comment by tw2113** [comment]
Shouldn't need to do that much, in terms of copying over the template file into your active theme. It should just be loading the one, which you can see an example of at https://github.com/WebDevStudios/wp-search-with-algolia/blob/2.1.0/templates/instantsearch.php

We run `get_header()` and `get_footer()` to get those global parts, but the rest is all custom and specific to the template.

Not sure what you may or may not be doing customizations wise, but it looks like once you get to the `<main class="main" role="main">` opening tag, entire templates are loaded again

**Comment by tw2113** [comment]
@marcperel did you ever get this one figured out?

**Comment by marcperel** [comment]
@tw2113 we found that our theme was erroneously adding an extra ```wp_head()``` to the site on specific templates, so we created a new search template which resolved the issue.

Thanks for following up! 💪
