### ISSUE TITLE
Search results change the order

### ISSUE THREAD

**Issue by orlovstepan** [WebDevStudios/wp-search-with-algolia#207]
Hi team, I am not sure if this is a bug or more like a plugin configuration that I can change (would be helpful if you let me know where/how).

When you go to [this page](https://falling-walls.com/lab/apply/) you see the results sorted from the most recent to the earliest. 

<img width="1311" alt="Screenshot 2022-04-05 at 14 42 57" src="https://user-images.githubusercontent.com/81413711/161737143-79e23570-7a02-4fab-a5c1-2622ea420dc9.png">

However, if you filter the results based on the region, the search results will appear in a reversed order (from the oldest to the newest). 

<img width="1318" alt="Screenshot 2022-04-05 at 14 43 44" src="https://user-images.githubusercontent.com/81413711/161737746-f7aa1757-b209-4ade-a182-ab826e1863b8.png">

I would like the results to appear in the order from the most recent to the oldest. Is there any way to change that on WordPress or in the plugin code?

Thanks in advance for your help! 

Best,
Stepan

**Comment by tw2113** [comment]
Are we certain that this page is using Algolia Search for it? I'm not really seeing any indications of instantsearch here. Or is it being used JUST for the WP_Query part and the results are being pushed back out front to this custom UI/filtering set up?

**Comment by tw2113** [comment]
@orlovstepan did you ever get this figured out? or is it still a lingering thing?

**Comment by tw2113** [comment]
Closing as a non issue for the time being. Feel free to respond if needed, with extra information.
