### ISSUE TITLE
Update InstantSearch.js Widget

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wp-search-with-algolia#21]
https://www.algolia.com/doc/api-reference/widgets/js/

**Comment by gregrickaby** [comment]
Update:

I've got the libraries (Algolia Search, InstantSearch, and InstantSearch CSS) being brought in via NPM, and bundled with WebPack in this branch: 

https://github.com/WebDevStudios/wp-search-with-algolia/tree/feature/refactor-from-scratch

**To Do:**

- [ ] Algolia's vanilla JS doesn't like to be bundled and is throwing an "ES" error. Why?
- [ ] Give developers a way to create simple CSS overrides, so they could customize the styles

**Comment by richaber** [comment]
> * Algolia's vanilla JS doesn't like to be bundled and is throwing an "ES" error. Why?

Import searchBox and hits from widgets.
 
```
import { searchBox, hits } from 'instantsearch.js/es/widgets';
```

Replace `instantsearch.widgets.searchBox` and `instantsearch.widgets.hits` with just `searchBox` and `hits`.

**Comment by richaber** [comment]
Closing, as of [WPSWA version 2.0.0](https://github.com/WebDevStudios/wp-search-with-algolia/releases/tag/2.0.0), we ship [Algolia InstantSearch.js version 4.25.2](https://github.com/algolia/instantsearch.js/releases/tag/v4.25.2)
