### ISSUE TITLE
Support for custom fields?

### ISSUE THREAD

**Issue by fabswt** [WebDevStudios/wp-search-with-algolia#210]
Is there any option to add the posts' custom field to the index?

**Is your feature request related to a problem? Please describe.**

I have a 'kicker' custom field, used for each post, that stores a catchy sentence describing the article (it's sometimes called the "lead" in newspapers.) I'd like to have it in the index, so I can show it in the search results, too. It often recaps a key value provided by the blogpost.

**Describe the solution you'd like**
An option to tick which custom fields we want in the index would be welcome.

**Describe alternatives you've considered**
I don't really see any alternative. If you don't have data in the index, you don't have it.

**Additional context**
Here's a screenshot [from my blog](https://bilingueanglais.com/blog/):

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/3042488/164420673-085b1e8d-d709-4643-a408-5170755a4567.png">

The 'kicker' is the indigo text above the title.

And here's a screenshot of search results:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/3042488/164421046-b01f4357-4bcc-4619-b376-d60ee6107055.png">

Would like to add the 'kicker' above each title.

Thank you for reading.

**Comment by tw2113** [comment]
Hi @fabswt I would check out https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Advanced-Custom-Fields. Even though it says ACF on the page, all the same code examples would apply for you except you'd use the WordPress core `get_post_meta()` instead of ACF's functions to fetch your field data.

Closing as not an enhancement/bug report, but we can continue the discussion still, as needed.

**Comment by braco** [comment]
Really surprised ACF support and custom post types aren't native with a UI.

**Comment by tw2113** [comment]
Hi @braco 

I'm a little confused, at least regarding the CPT part, as we've had support for indexing post types from pretty much the getgo. The Autocomplete settings page lists them and provides UI on whether or not to give them an index. The Search/InstantSearch settings page has been including any that are listed as "searchable" automatically. In a sense it's more a case of having to manually remove if you don't want a given post type indexed.

On the custom field side, yeah that's a bit more on the manual/code level to get included, but definitely possible. Doing anything around UI for custom fields, whether it be with ACF, Pods, or any other solution is not an easy undertaking to attempt. Thus why we at least leave it at a code level method, which as pointed out in my previous comment, is hopefully pretty straightforward and can be done with only a few lines of code. Trying to provide UI to handle custom fields for all the potential post types feels...daunting.
