### ISSUE TITLE
Disabling autocompleting, but not indexing (interface)

### ISSUE THREAD

**Issue by fabswt** [WebDevStudios/wp-search-with-algolia#211]
**Describe the bug**
This is not as much as a bug report as it is feedback on the interface:

When disabling Autocomplete in the settings, because of how things are laid out, it's not obvious (at least not to me) whether this disables indexing of the data as well:

<img width="1556" alt="image" src="https://user-images.githubusercontent.com/3042488/165041669-89226f65-c502-419a-bba2-90fe961fe5b1.png">

(In practice (from testing), disabling autocomplete does not impact the indexing setup below the "Enable autocomplete" option.)

**Expected behavior**
I would suggest maybe renaming "Configuration" to "Index configuration" and adding a separation between the "Autocomplete" and "Indexes" option, or a quick clarifying message. (Or having both live on different pages.)

**Additional context**

Background: using wp-search-with-algolia to automatically push the blogposts to Algolia's index, but using my own autocomplete (shared across our WordPress blog and a non-WordPress main section of the site) for the search widget and autocomplete. Needed to disable the autocomplete option to prevent clashes and JavaScript errors between my own autocomplete and the plugin's (`Uncaught TypeError: autocomplete.noConflict is not a function` / `Uncaught ReferenceError: algoliaAutocomplete is not defined`), which is all fine. Just wasn't sure of the impact on the indexes then because of the settings' layout.

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/wp-search-with-algolia/pull/307
