### ISSUE TITLE
Add filter to potentially override Autocomplete enabled status.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#218]
We have `should_override_search_with_instantsearch()` in `class Algolia_Settings` and I think it would be useful to have a matching version for Autocomplete.

```
public function should_override_search_with_instantsearch() {
	$value = $this->get_override_native_search() === 'instantsearch';

	return (bool) apply_filters( 'algolia_should_override_search_with_instantsearch', $value );
}
```
I am seeing support requests where users want to use the functionality only in some places of their website, and not globally. The filter above covers instantsearch, but not autocomplete.

**Comment by asharirfan** [comment]
@tw2113 

> I am seeing support requests where users want to use the functionality only in some places of their website, and not globally.

I am assuming by this, you mean that the users want to enable the autocomplete on some specific pages or locations and disable on the rest?

**Comment by tw2113** [comment]
I believe so, yes. Allow the ability to filter a boolean value conditionally, much like one could with the existing code above.

**Comment by tw2113** [comment]
Closing as handled in #245
