### ISSUE TITLE
Customization Request.

### ISSUE THREAD

**Issue by kamal87g** [WebDevStudios/wp-search-with-algolia#219]
Hi Team,
I need few things as below. 
1: Add Author name and archive link to a blog post for index.
2: How to add Product Price for index.
3:  Customized layout as like this page algolia search https://simplifaster.com/search/

![image](https://user-images.githubusercontent.com/16898100/173621852-b0bfccd6-cabb-448b-9172-15b775703025.png)

**Comment by tw2113** [comment]
For adding custom things to be included as part of the index, you can make use of the code sample over at https://webdevstudios.com/2021/02/09/wp-search-with-algolia/#indexing-custom-fields

Then in the instantsearch template file, you'd be able to make use of that information by referencing the appropriate variable like so: `{{{ data.footer_content }}}`. If you named the shared attribute "price", you'd change it to `{{{ data.price }}}` and output in the desired location. Note that it doesn't need to be just custom fields, any sort of string information you want to store on a given index can be done. You should already have author and permalink information in the `data` variable. Basically anything on a given object when viewing in your Algolia dashboard is on that `data` variable for each object.

Regarding layout, I'm not quite sure how exactly they separated things out like that, but obviously it looks like it's possible overall. Looks like their active theme comes with some InstantSearch integration, which is probably handling most of it.

**Comment by tw2113** [comment]
Closing as a non issue that needs changed in the plugin code itself. This was a customization help request.
