### ISSUE TITLE
Update documentation to reflect removal of "blacklist" verbiage.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#223]
Looking at https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks and we have reference to `algolia_post_types_blacklist` which got deprecated in favor of `algolia_excluded_post_types` in version 1.7.0 from the looks of it.

We should review the documentation to update any references to the deprecated "blacklist" wording.

**Comment by leadoux** [comment]
I'm getting warning of this in my debug.log file.

`[04-Jul-2022 09:02:07 UTC] PHP Deprecated:  algolia_post_types_blacklist is <strong>deprecated</strong> since version 1.7.0! Use algolia_excluded_post_types instead.`

**Comment by tw2113** [comment]
Hey @leadoux do you have any custom code around WP Search with Algolia being used for your install? If yes, especially around this specific topic, you'll want to update the hook mentioned to match. I've checked the codebase for the plugin itself and the `algolia_post_types_blacklist` hook is only mentioned in the one spot where we've marked it as deprecated.

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks is the only wiki page that has it mentioned.

**Comment by tw2113** [comment]
Fixed up in https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks/_compare/a382cc3d7b48433575a63d8915c60f4ca6373818...2e80c65b67ea0aa2560f86e127f868d910b58592
