### ISSUE TITLE
Test and ensure templates still render properly when scripts are moved to footer.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#227]
In cases of users optimizing their sites for performance, they may be moving their script loading to the footer area of their pages, including jQuery.

Both templates make use of jQuery out of box for parts of their functionality, and if there's ways to ensure that the templates don't encounter "jQuery not defined" errors, when jQuery does get loaded eventually, then we should make use of those methods.

Is there a way to harden up the templates to work as expected, regardless of placement, without having to have "2 different versions"

**Comment by eSaner** [comment]
@tw2113 any progress to report on this? Would love to see it resolved. Removing jQuery as a dependency for templates would be great, but even just a filter to control the wp_footer priority would work for me.

For example, on line 61 of class-algolia-template-loader.php:

`add_filter( 'wp_footer', array( $this, 'load_autocomplete_template' ) );`

could be changed to:

`add_filter( 'wp_footer', array( $this, 'load_autocomplete_template' ), apply_filters( 'algolia_footer_script_priority', 10 ) );`

**Comment by tw2113** [comment]
No news on our front.

Given that all the jQuery dependency is in the templates themselves, and the fact that users are able to customize the templates safely through their theme, shouldn't necessarily hold anyone up.

https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Customize-Templates

The only jQuery dependencies in the autocomplete.php file are "document ready" and some foreach loops, and a click event listener, all of which could easily be replaced. The instantsearch.php template has a "document ready" and a length selector, and search input select trigger.

I won't argue that we could probably, for the best, replace these, but just hasn't been done thus far.

**Comment by eSaner** [comment]
I replaced the jQuery in autocomplete.php and have it working now with jQuery loaded in the footer. But note that under /* Setup dropdown menus */ in autocomplete.php

`document.querySelectorAll(algolia.autocomplete.input_selector);`

didn't work because the algolia_autocomplete_input_selector filter returns

`input[name=s]:not('.no-autocomplete')`

and querySelectorAll doesn't work when css :not() has quotes around the selectors.  Using the filter to remove the quotes fixed it, but it should work without quotes for jQuery too, so they could just be removed regardless.

**Comment by tw2113** [comment]
Sounds like we have some of the potential edits needed to remove the jQuery dependency, but not all of them.

**Comment by tw2113** [comment]
This task is likely going to be closable once #247 is verified and finalized.

We are moving away from making use of jQuery in the templates.
