### ISSUE TITLE
Mixed Index with MultilingualPress

### ISSUE THREAD

**Issue by swissky** [WebDevStudios/wp-search-with-algolia#229]
Hey together,

A client of us used MultilingualPress for presenting the Webpage in different Languages. Each Language is a new WP Site in a Multisite Construct. 

Now we installed the Algolia Plugin on each of this site and created a different Index for each Language, so we don't have mixed stuff in the searchresults. But exactly this problem happens. If a user is searching for a product, all 3 language are visible.

Do you have any idea? All Languages are on different indexes and on different sites.

Best Kevin

**Comment by tw2113** [comment]
Do you have a URL that we could try this out with and see first hand?

**Comment by tw2113** [comment]
@swissky wanted to followup to see if any new developments have been found or perhaps solutions, or even fixes that were added. We coincidentally have someone else with a very similar problem so anything you found could help them.

**Comment by tw2113** [comment]
Have had some discoveries going on over at https://wordpress.org/support/topic/re-indexation-mixes-posts-from-the-different-subsites/

**Comment by tw2113** [comment]
The support thread above has some filters and snippets that worked for that author. Hopefully @swissky can make use of the same until we determine how we potentially want to integrate ourselves.

**Comment by tw2113** [comment]
Closing this due to lack of further feedback, and based on available filtering tools and documentation regarding internationalized content.

If we need to return to it in the future, we can.
