### ISSUE TITLE
`Fatal error: Uncaught TypeError: PHP 8.1.x

### ISSUE THREAD

**Issue by mrEckendonk** [WebDevStudios/wp-search-with-algolia#238]
**Describe the bug**
unable to activate the plugin. Works with PHP 7.4.x

**Additional context**
`Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "WDS_Headless_Algolia\activation_callback" not found or invalid function name in /home/nginx/domains/backoffice.xx/public/wp-includes/class-wp-hook.php:307 Stack trace: #0 /home/nginx/domains/backoffice.xx/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #1 /home/nginx/domains/backoffice.xx/public/wp-includes/plugin.php(476): WP_Hook->do_action() #2 /home/nginx/domains/backoffice.xx/public/wp-admin/plugins.php(194): do_action() #3 {main} thrown in /home/nginx/domains/backoffice.xx/public/wp-includes/class-wp-hook.php on line 307`

**Comment by tw2113** [comment]
Hey @mrEckendonk Are you using some other codebase from WebDevStudios that interacts with Algolia as well as our plugin here? Asking because I'm not finding any reference to `WDS_Headless_Algolia` in this code, so it feels like this issue is more for a different codebase.

**Comment by mrEckendonk** [comment]
@tw2113 I used https://github.com/WebDevStudios/nextjs-wordpress-starter and all relevant plugins.

**Comment by tw2113** [comment]
Hmm, not seeing that namespaced function and whatnot in the nextjs-wordpress-starter repo, but am in the one I linked to.

Odd because it's calling a function as a registration hook, in a file that doesn't appear to be getting loaded. I wonder if we need to add a couple more require_once's to https://github.com/WebDevStudios/wds-headless-algolia/blob/main/wds-headless-algolia.php

**Comment by mrEckendonk** [comment]
There are more open issues about the plugins related to PHP 8.x.x https://github.com/WebDevStudios/nextjs-wordpress-starter/issues/958

**Comment by tw2113** [comment]
Good find, and sounds like we have some work to be doing on things. Because of that issue being open, and covered by other places. I'm going to close this issue on our plugin here.
