### ISSUE TITLE
Verify our hooks, filters, constants list in documentation is current and accurate.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#240]
What the title says.

**Comment by tw2113** [comment]
Filters page has been updated to match what we have in version 2.2.0

https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks

**Comment by tw2113** [comment]
Marking this as done as the wiki is uptodate as of version 2.6.1

**Comment by samfrank** [comment]
@tw2113 Is there somewhere that lists what the filter/ action do? I can see the lists [here](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks) and [here](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Action-Hooks), but these only show what params they except.

**Comment by tw2113** [comment]
At least based on current documentation, visiting the hooks in the code would be best. I know some of them have inline documentation already, and I also have https://github.com/WebDevStudios/wp-search-with-algolia/tree/feature/363-action-filter-docs in review that fills in the rest.
