### ISSUE TITLE
CPT Shared Attributes filter not running on reindex & save for CPT Index

### ISSUE THREAD

**Issue by timbolimboslice** [WebDevStudios/wp-search-with-algolia#242]
**Describe the bug**
I have a custom post type that, on post save or reindexing (triggered from the Autocomplete admin page), does not seem to fire the `algolia_searchable_post_{$post_type}_shared_attributes` filter. I'm able to set breakpoints in the plugin to see that the proper record information is sent to the "All Posts" index, but that information seems to be missing when the record is pushed to the CPT's index. Basic information (like post_title) is updated properly in the CPT's index, just information that is defined in the CPT shared attributes filter.

**Expected behavior**
I should be seeing the same record data in each index.

**Screenshots**
![Index List on the "Autocomplete" admin page](https://user-images.githubusercontent.com/11657201/195689338-5abe3dc2-53ff-403b-a6c6-fdb048950ce5.png)
**Index List on the "Autocomplete" admin page**

![List of Indices in Algolia](https://user-images.githubusercontent.com/11657201/195689404-54cf10bf-0b94-40fa-bfd8-4eb7756c55f0.png)
**List of Indices in Algolia**

![Screenshot of CPT shared attributes filter](https://user-images.githubusercontent.com/11657201/195693181-cf72621c-a9b7-4db1-a835-8207eecceb27.png)
**Screenshot of CPT shared attributes filter**

![Screenshot of Request Body for CPT Index, note the missing additional image sizes](https://user-images.githubusercontent.com/11657201/195693593-48701ca5-2fca-40dc-b4e0-8a22c9dfa9f1.png)
**Screenshot of Request Body for CPT Index, note the missing additional image sizes**

![Screenshot of Request Body for the "All posts" Index, note the additional image sizes](https://user-images.githubusercontent.com/11657201/195693763-ed9e8bfa-ad49-44cb-9b6f-9bbec3122376.png)
**Screenshot of Request Body for the "All posts" Index, note the additional image sizes (even though the request body is truncated).**

**Comment by tw2113** [comment]
Hi @timbolimboslice 

Since you're wanting to do this shared attributes detail in with the autocomplete, you'll want to use these filters instead:

`algolia_post_shared_attributes` or `algolia_post_' . $post->post_type . '_shared_attributes`

The one you're using with "searchable" in the filter name is meant for the InstantSearch/Search Page settings. Bit of an easy mistake to make, but hopefully that switch gets what you need handled and indexed.

**Comment by timbolimboslice** [comment]
Hi @tw2113 

Removing the "searchable" from the filter name worked for me. Thanks for your help and quick reply.

**Comment by tw2113** [comment]
Welcome
