### ISSUE TITLE
Update default excluded post types and taxonomies

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#244]
We haven't really touched the default excluded post types and taxonomies in awhile, and there have definitely been new ones added in the background. We also "litter" the autocomplete page with a lot of content types that chances are users aren't ever going to be needing to index, and really shouldn't.

We can either manually update the lists found in https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/class-algolia-settings.php#L122-L166 and https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/class-algolia-settings.php#L224-L251

or

perhaps we should amend our `get_post_types()` and `get_taxonomies()` calls to fetch non-built in content types? We can always re-add `posts`, `pages`, `attachments`, `category`, and `post_tag` into our resulting array, just those would be "hardcoded".

Post types that are being added that are from and for WP core, that aren't excluded yet:

* custom_css
* customize_changeset
* oembed_cache
* user_request
* wp_block
* wp_global_styles
* wp_navigation
* wp_template
* wp_template_part

All are marked as `public => false` and `_builtin => true`.

On the taxonomy front, we have:

* wp_theme
* wp_template_part_area

Not as many to update, but still would be good to get included.

**Comment by tw2113** [comment]
We can remove `algolia_task` and `algolia_log` from our excluded list as they were used before the original 2.0.0 release of Algolia's version of the plugin and since removed.

https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/class-algolia-settings.php#L154-L156

**Comment by asharirfan** [comment]
Fixed in #248
