### ISSUE TITLE
Update any logo/icon usage to match Algolia's 2022 rebranding

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#246]
https://algolia.frontify.com/d/1AZwVNcFZiu7/style-guide

<img width="535" alt="Screen Shot 2022-10-20 at 11 57 23 AM" src="https://user-images.githubusercontent.com/484075/197011846-883bc9da-b36d-4a64-b302-07cc41da5acf.png">

**Comment by tw2113** [comment]
I have the admin menu logo touched up already in 246-update-algolia-logos branch, however, the "Powered by" spot is proving troublesome for me to get accurately sized while not messing up some of the paths used for the SVG. Maybe something to re-try tomorrow.

**Comment by asharirfan** [comment]
Fixed in #252
