### ISSUE TITLE
Simple Options Page

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wp-search-with-algolia#25]
The current implementation of the backend is complex. I'd like to simplify this, and focus our efforts on making a developer friendly plugin, that holds it's core values close to that of Algolia. In other words, let the dev customize it vs. forcing opinionated backend code and front-end styles. 

Yes, it should still be released on WordPress.org, but the options page should be simplified and we should leverage WP-CLI for building and updating indexes.

**Comment by hi-im-si** [comment]
Things like Synonyms i believe should be managed from a UI
