### ISSUE TITLE
Autocomplete not initializing after jQuery removal

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#258]
we tried `window.onload = function () { ... }` with instantsearch but switched to `addEventListener` since it was not initializing.

Here in autocomplete we have the same `window.onload = function () {` attempt but we never fixed it to match:
https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/templates/autocomplete.php#L75-L78

Should get changed to match.

**Comment by asharirfan** [comment]
This issue has been fixed in v2.3.1
