### ISSUE TITLE
Buddy deploys to WordPress.org

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/wp-search-with-algolia#26]
Let's have a machine build and deploy the artifacts to WordPress.org plugin repo. This ties in with #24 a little bit, in that our build pipeline should run lots of tests prior to new releases.

Also, @richaber mentioned a Gulp workflow to turn Readme.MDs into Readme.txt. Figure this out!

**Comment by richaber** [comment]
@gregrickaby this is interesting, but I don't think it runs a build process: https://github.com/marketplace/actions/wordpress-plugin-deploy

**Comment by richaber** [comment]
> Gulp workflow to turn Readme.MDs into Readme.txt

IIRC, the WP-CLI scaffold plugin command uses this [grunt-wp-readme-to-markdown
](https://github.com/stephenharris/wp-readme-to-markdown)

**Comment by richaber** [comment]
Closing in favor of #168
