### ISSUE TITLE
Display content from a custom field in ['content'] within instantsearch.php for CPT's

### ISSUE THREAD

**Issue by danmaby** [WebDevStudios/wp-search-with-algolia#263]
Hi

**Is your feature request related to a problem? Please describe.**
I would like to replace the content displayed when `if ( data._snippetResult['content'] )` within instantsearch.php (<a href="https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/templates/instantsearch.php#L62">line 62</a>) is called with content from a custom field, if a post from the `allc_therapist` custom post type is returned in the search results. 

**Describe the solution you'd like**
I have a custom field called `allc_therapist_practice_overview ` that is being indexed by Algolia: 

![Screenshot 2022-11-14 at 15 33 40](https://user-images.githubusercontent.com/13104185/201704248-69b0ecc4-48f7-49b6-aad1-f572ac78eaec.png)

I would like to display this content within the instantsearch.php results when the custom post type `allc_therapist` is displayed. As this CPT has no `the_content` field, the returned results have an empty space:

![Screenshot 2022-11-14 at 16 03 46](https://user-images.githubusercontent.com/13104185/201707938-1b8e70dc-609e-4daa-87a4-64fb41564e59.png)

**Describe alternatives you've considered**
I wrote a <a href="https://gist.github.com/danmaby/791ba2e20b262ae927d1b807fe791889">filter</a> to return the custom field `allc_therapist_practice_overview` as the excerpt for the `allc_therapist` custom post type. But the wp-search-with-algolia plugin appears to ignore the excerpt and only returns content from `the_content`. 

**Additional context**
I appreciate this isn't an issue, and if beyond the scope of any support here, please close.

**Comment by tw2113** [comment]
My biggest question is do you have all the content intended being indexed on the correct Algolia index objects? If yes, then it's going to just be a matter of checking for the specific properties above being present on the returned result. For example: `<# if ( data.allc_therapist_practice_overview ) { {{ data.allc_therapist_practice_overview }} } #>` if I'm not mistaken on formatting.

**Comment by tw2113** [comment]
Regarding length, you'd either need to trim it down before indexing, or make use of the transformItem parameter of the hits widget https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/#modify-the-list-of-items-in-widgets to trim down with javascript. I don't have any specific examples of how to do that part though.

For the second question, you'd need to make certain that the attribute in question is listed as searchable in your Algolia dashboard.

**Comment by danmaby** [comment]
I appreciate your help with this @tw2113.
