### ISSUE TITLE
Custom override location for template files that are not the active theme.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#264]
Make it possible to override the default instantsearch and autocomplete files without requiring loading from the active theme.

Would help with site builds and customization without tying directly to the theme. Filter name not final.

## Proposed filter

```
public static function locate_template( $file ) {

	$custom_override = apply_filters( 'algolia_non_theme_location', null, $file );

	if ( ! empty( $custom_override ) ) {
		return $custom_override;
	}

	$locations = [
		$file,
	];

	...
}
```
This filter would return early in our utility function if it is given anything but null back.

Example filter usage, with working but dummy code:

```
define( 'DUMMY_PLUGIN_BASENAME', plugin_basename( __FILE__ ) );
define( 'DUMMY_PATH', __DIR__ . '/' );

function test( $override, $file_name ) {
	if ( ! file_exists( DUMMY_PATH . 'templates/' . $file_name ) ) {
		return $override;
	}

	return DUMMY_PATH . 'templates/' . $file_name;
}
add_action('algolia_non_theme_location', 'test', 10, 2);
```

**Comment by tw2113** [comment]
Listing this as a DRAFT PR since we don't have a release branch ready for a next release yet.

https://github.com/WebDevStudios/wp-search-with-algolia/pull/269

**Comment by tw2113** [comment]
PR is ready https://github.com/WebDevStudios/wp-search-with-algolia/pull/269

**Comment by scottbasgaard** [comment]
@tw2113 dropping reminder here to update https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks before closing issue.

**Comment by tw2113** [comment]
See https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks/_compare/22223efa8a3a21835a7d0ef6191fda38e611baa4...5b65722c73c7bc1e1342fb14355816a8593d0de4
