### ISSUE TITLE
Namespace conflicts with Simply Static Pro plugin.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#266]
They bundle the AlgoliaSearch PHP client with their plugin as well.

https://patrickposner.dev/plugins/simply-static/

https://wordpress.org/support/topic/namespace-conflict-with-other-plugin/

**Comment by richaber** [comment]
@tw2113 you could look into [Strauss](https://github.com/BrianHenryIE/strauss) or [PHP-Scoper](https://github.com/humbug/php-scoper) to prefix dependencies. I believe I had a couple of experimental branches laying around ([like this one](https://github.com/WebDevStudios/wp-search-with-algolia/tree/try/strauss)) to do just that, but as I recall, I held off _at the time_ to avoid "yet another major/breaking version release."

**Comment by cw-richaber** [comment]
@tw2113 I should also mention the `algolia_should_require_search_client` filter that does _currently_ exist. You could mention it to the issue reporter on dotorg as a potential workaround for the moment...

From the [Wiki](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks):
| Filter Name                                                  | Params                                                                                                        |
|--------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|
| algolia\_should\_require\_search\_client                     | bool $bool, (default: true, loads the included Algolia search client library)                                 |

**Comment by pixeline** [comment]
Hi! Thank you for creating this ticket! As a potential solution Delicious Brain has this suggestion: https://deliciousbrains.com/php-scoper-namespace-composer-depencies/

**Comment by richaber** [comment]
@asharirfan / @tw2113 I've opened a PR for this (#267) if y'all wanna give it a look.

**Comment by tw2113** [comment]
Closing this as it will be part of version 2.4.0 and we have already merged the PR.
