### ISSUE TITLE
Nothing happens after Reindexing

### ISSUE THREAD

**Issue by NiVoodo** [WebDevStudios/wp-search-with-algolia#275]
Hi,

I have the problem that re-indexing (searchable posts and products) stops after 0%.

Indexes in algolia are deleted but nothing new is uploaded in Searchable Posts. 
Autocomplete stops product indexing after 0%, but exactly 100 products are indexed in algolia.

![image](https://user-images.githubusercontent.com/119708934/205404215-f74e720e-9277-4f49-9bec-5239ffd3bd33.png)

Changing the algolia account and API credentials does not fix the problem. 
The push settings are working correctly. 

I can't tell what is causing the problem - everything is working pretty well. After trying to change the Instantsearch page, we found that there are no more updates for products. 

Uninstalling and reinstalling does not help. However, I noticed that the credentials entered in the settings are still there after the reinstall. 

I hope you can help me to get to the reason of the error.

**Comment by NiVoodo** [comment]
[](url)

**Comment by tw2113** [comment]
Have you checked error logs at all? It's possible some sort of error on the server could be preventing the POST requests to fail.

Alternately, I'm wondering if things would happen differently with WP-CLI https://wp-cli.org/

Example commands that work with WP Search with Algolia:

```
# Reindex content for the `posts_post` index...
wp algolia reindex posts_post
# Reindex content for all enabled indices...
wp algolia reindex --all
# Reindex content for all enabled indices, clear existing records first...
wp algolia reindex --clear --all
```
You'd want to try `wp algolia reindex searchable_posts` if I'm not mistaken.

https://github.com/WebDevStudios/wp-search-with-algolia/wiki/WP-CLI
