### ISSUE TITLE
Flatsome theme not replacing the existing search results

### ISSUE THREAD

**Issue by sollylabs** [WebDevStudios/wp-search-with-algolia#276]
I have tried both options
1. Use Algolia in the backend
2.  Use Algolia with Instantsearch.js
In both cases, flatsome search results appear along with algolia search results. 
Any way to replace the search results. 

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/66559351/205492288-d3665102-cf15-4c77-b3ba-a2e8ec998fd9.png">
www.sollylabs.com

**Comment by tw2113** [comment]
Are there any settings available in Flatsome to disable their search? It feels like both are being used at the same time?

**Comment by tw2113** [comment]
Did you ever solve this @sollylabs ?

**Comment by tw2113** [comment]
Closing for the time being due to no updated feedback. Feel free to re-comment with new status and extra information, as needed.
