### ISSUE TITLE
Index Setting aroundLatLngViaIP

### ISSUE THREAD

**Issue by nathan-schmidt-viget** [WebDevStudios/wp-search-with-algolia#277]
**Describe the bug**
I need to set a custom post setting for `aroundLatLngViaIP`. In my `add_filter( 'algolia_posts_index_settings', 'service_settings' );` But when I try and sync the settings I get `An error occurred`

**To Reproduce**
Place this in function for custom index setting. 
```
$custom_ranking = $settings['aroundLatLngViaIP'];
array_unshift( $custom_ranking, 'true' );
$settings['aroundLatLngViaIP'] = $custom_ranking;
```

**Expected behavior**
Add `aroundLatLngViaIP` to the api parameters - https://www.algolia.com/doc/api-reference/api-parameters/aroundLatLngViaIP/?client=php

**Comment by tw2113** [comment]
@nathan-schmidt-viget can you check your error logs for any errors that happened around that time? It sounds like a PHP error is occurring and preventing the request from completing

**Comment by nathan-schmidt-viget** [comment]
@tw2113 I looked at the log for my ddev and found that `$custom_ranking` was being set to an array. 
If I change ` $custom_ranking` to ` $custom_ranking[]` I get the error `FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "aroundLatLngViaIP"`

**Comment by tw2113** [comment]
Also if this is part of the Personalization API/areas of Algolia, then I don't have a personal plan high enough to access/test much.

That said, the setting is a true/false value so I'm not quite sure why you're using array_unshift and whatnot. Lastly, have you confirmed that you have that index already in the incoming settings? Otherwise, perhaps just set it, and make sure to do boolean `true` and not string `'true'` since I believe they're a little picky on parameter types.

**Comment by nathan-schmidt-viget** [comment]
Thanks @tw2113,  it is not part of the Algolia personalization API. But a parameter under [GeoSearch](https://www.algolia.com/doc/api-reference/api-parameters/aroundLatLngViaIP/?client=php)

Ya I had the whole array_unshift and whatnot as that is what I saw in [the plugin docs](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Index-Settings#custom-index-settings-example) Originally had `$settings['aroundLatLngViaIP'][] = true;` which gives me the same error `Invalid object attributes: aroundLatLngViaIP `

Here is my `post_settings` function that is called by two different post types. 

```
/* algoliaSync.php */
/**
 * post_settings function
 *
 * @param array $settings
 * @param array $postFields
 * @return $settings
 */
function post_settings( array $settings, $postType, $postFields) {

    // Eligible post meta fields.
    foreach ( $postFields as $field ) {
        $settings['attributesToIndex'][] = 'unordered('.$field.')';
	}

    if ($postType == 'provider'){
        $settings['attributesForFaceting'][] = 'services.post_title';
        $settings['attributesForFaceting'][] = 'locations.post_title';
        $settings['hitsPerPage'][] = 10;
    }

   if ($postType == 'location'){
        $settings['attributesForFaceting'][] = 'services.post_title';
        $settings['hitsPerPage'][] = 10;

        $settings['aroundLatLngViaIP'][] = true;
    }

    return $settings;
}

```

**Comment by nathan-schmidt-viget** [comment]
The only place I see it in Algolia is under Add Query Parameter > Geo-Search. But you could be right that it is a part of the props that can be passed in on the frontend.

**Comment by tw2113** [comment]
Did you ever figure out a solution for this @nathan-schmidt-viget ?

**Comment by nathan-schmidt-viget** [comment]
@tw2113 Yes, the solution is in Algolia by using [Configure](https://www.algolia.com/doc/api-reference/widgets/configure/react/).

```
 <InstantSearch indexName={index}>
   <Configure aroundLatLngViaIP="true" aroundRadius="all" />
 </InstantSearch>
```
