### ISSUE TITLE
algolia_search_params not working

### ISSUE THREAD

**Issue by kakashigr** [WebDevStudios/wp-search-with-algolia#278]
**Describe the bug**
I am trying to use the algolia_search_params filter to add some filters on the search results, but they don't seem to be working. No matter what filters I try to add, they won't work. Even  tried overwriting 'hitsPerPage' doesn't work with this filter hook. 

**To Reproduce**
in theme's functions.php: 
    function my_algolia_query_filters($params) {
		$params['filters'][] = ["excluded != 1"];
		return $params;
	}
	add_filter('algolia_search_params', 'my_algolia_query_filters', 10, 1);

**Expected behavior**

Viewing the correct index search logs in algolia dashboard, shows the request body without any filters:

{
  "query": "moon",
  "hitsPerPage": 5,
  "attributesToSnippet": [
    "content:10"
  ],
  "highlightPreTag": "__ais-highlight__",
  "highlightPostTag": "__/ais-highlight__"
}

**Additional context**
Using latest Wordpress version and latest plugin version.

**Comment by tw2113** [comment]
Have you pushed your index settings yet? The filters for settings don't auto deploy, so you need to push them to get them into your dashboard.

**Comment by kakashigr** [comment]
I did, not change. These are filters for the actual search query though so it shouldn't matter either way

**Comment by tw2113** [comment]
Try changing `$params['filters'][] = [ "excluded != 1" ];` to `$params['filters'] = [ "excluded != 1" ];` It looks like your code above is creating a nested array which may be affecting things.

Since I know we have some amount of logging, when WP_DEBUG is enabled and whatnot, I am seeing this in my debug.log file:

```[16-Dec-2022 16:57:05 UTC] filters: Unexpected token string(excluded != 1) expected end of filter at col 4
```

**Comment by kakashigr** [comment]
Tried that. Also tried changing the priority of the filter from 10 to 999999. Still nothing.
The request body in algolia search logs is still completely missing it:

```
{
  "query": "bored ape key items",
  "hitsPerPage": 5,
  "attributesToSnippet": [
    "content:10"
  ],
  "highlightPreTag": "__ais-highlight__",
  "highlightPostTag": "__/ais-highlight__"
}
```

**Comment by tw2113** [comment]
Hmm.

At least in terms of what's being sent to Algolia, from our side, I'm seeing the following right before the request is made:

<img width="710" alt="Screen Shot 2022-12-16 at 11 10 01 AM" src="https://user-images.githubusercontent.com/484075/208151866-8c6f04e3-1fc0-4b42-bd7f-70fe3884b56e.png">

This is with just

```
function my_algolia_query_filters( $params ) {
	$params['filters'] = [ "excluded != 1" ];

	return $params;
}
add_filter( 'algolia_search_params', 'my_algolia_query_filters', 10, 1 );
```
Are you checking the values before or after they've been returned from Algolia?

**Comment by kakashigr** [comment]
I was looking at the search logs in Algolia dashboard, the request body specifically. 
No sign of it in the browser request either.
![image](https://user-images.githubusercontent.com/4283743/208164868-9891b90e-157d-4256-adf2-ccb904db040b.png)

Btw this is from the live Autocomplete search, i.e. when you type in a searchbox, not when you hit enter

**Comment by kakashigr** [comment]
Btw, tried disabling all plugins except algolia, still the same. Its so weird.

**Comment by kakashigr** [comment]
So it appears the Autocomplete does not respect this filter at all.

I ended up copying the templates/autocomplete.php file to my theme:
algolia/autocomplete.php

And manually change this:
![image](https://user-images.githubusercontent.com/4283743/208170845-88392d03-cca2-4272-874f-92a439559824.png)

This is the only thing that works.

So, to summarize, the autocomplete does not take into account the filters at all.

**Comment by tw2113** [comment]
Ahh, yeah that's making sense. I'm checking the filter in the code and it's only being used for `pre_get_post` query altering, which is going to act on searchable_posts index only, not Autocomplete.

Customizing the Autocomplete template that way would thus be the best way to handle.
