### ISSUE TITLE
Update "Settings" header in Settings page to read "Algolia Settings"

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#279]
We can leave the menu text at just "Settings" but I think we should clarify what the settings are for a little bit more on-page.

**Comment by williamsba** [comment]
Updated in my settings revamp branch https://github.com/WebDevStudios/wp-search-with-algolia/commit/c3c2e626b2502e1d7890b0ba0ae0985a0c4c5d61

**Comment by tw2113** [comment]
See https://github.com/WebDevStudios/wp-search-with-algolia/tree/settings-revamp

**Comment by tw2113** [comment]
https://github.com/WebDevStudios/wp-search-with-algolia/pull/289

**Comment by tw2113** [comment]
Since we merged already, closing as resolved.
