### ISSUE TITLE
Integrating google map

### ISSUE THREAD

**Issue by arizonal2014** [WebDevStudios/wp-search-with-algolia#283]
This is like asking for a suggestion than an issue. Any advice on how to go about loading Google maps library and then showing the location on the map as the user start searching? Similar to this [Link example](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/instantsearch.js/geo-search-tourism)

My attempt was to load the google map in the script tag in instantsearch.php file but I am having issues with how to dynamically send the latitude and longitude from my return hits to the loaded map.

`var script = document.createElement('script')
		script.src = 'https://maps.googleapis.com/maps/api/js?key=XXXXXXX&callback=initMap';
		script.async = true;

		// Attach your callback function to the `window` object
		window.initMap = function() {
	map = new google.maps.Map(document.getElementById("geo-search"), {
    	center: { lat: 59.334591, lng: 18.063240, },
    	zoom: 8,
  		});
	};`

I will appreciate any help or suggestion on how to achieve this.

**Comment by tw2113** [comment]
Hi @arizonal2014 

Looking at the example you provided, it actually looks pretty straightforward overall. The `src/app.js` is pretty familiar to what we use already in the instantsearch.php template file.

the only parts I'm seeing that are geolocation related are the following parts:

```
instantsearch.widgets.configure({
  aroundLatLngViaIP: true,
  hitsPerPage: 12,
}),
```

```
instantsearch.widgets.geoSearch({
  container: '#map',
  googleReference: window.google,
  enableRefineControl: false,
  builtInMarker: {
    createOption: function(hit) {
      return {
        title: hit.description,
      };
    },
  },
}),
```
It seems once a couple of widgets get configured, Algolia is able to figure a lot of things out themselves though I'm also definitely curious how it seem the example knows with part of the index is the latitude/longitude field. However I could see that being a configuration setting too, not needed in the instantsearch JS

**Comment by arizonal2014** [comment]
Thank you very much. I give it a try.

**Comment by tw2113** [comment]
@arizonal2014 Did some tinkering and testing things out with that example above.

As long as you get geolocation information added to your objects, as per https://www.algolia.com/doc/guides/managing-results/refine-results/geolocation/, Algolia does pick up on it all.

I added the google maps js script ala:

`<script src="https://maps.googleapis.com/maps/api/js?v=weekly&key=API_KEY_HERE"></script>
`

and then add in a div to store the map. 

Lastly the following two parts:

```
instantsearch.widgets.configure({
	aroundLatLngViaIP: false, //Note this was originally true in the example above.
	hitsPerPage      : 12,
}),

instantsearch.widgets.geoSearch({
	container          : '#map',
	googleReference    : window.google,
	enableRefineControl: false,
	builtInMarker      : {
		createOption: function (hit) {
			return {
				title: hit.description,
			};
		},
	},
}),
```

Tested it all out and got the following result:

<img width="696" alt="Screen Shot 2022-12-28 at 7 53 36 PM" src="https://user-images.githubusercontent.com/484075/209893282-adf45878-74fc-4e54-afb6-784a8d3143c4.png">

All pretty straightforward in the end, as long as you get the latitude and longitude on your objects in the correct way.

**Comment by arizonal2014** [comment]
Hello!

Thanks you very much for the reply. In which file did you add the script in? my approach was to add the script in the theme function.php file as `function customGoogleMapScript () {
	?>
	<script src="https://maps.googleapis.com/maps/api/js?v=weekly&key=APIKEY">
	 </script> 
 <?php
}

add_action('wp_head', 'customGoogleMapScript');`

In loading the maps javascript API via https://developers.google.com/maps/documentation/javascript/overview#Loading_the_Maps_API

a call back function is needed to initialize the map.

That was my initial step to get the map loaded. How did you init the map?

Thank you in advance.

**Comment by tw2113** [comment]
I just used the instantsearch.php file that ships with the plugin, but anywhere where you could get the maps script tag into the page would be fine.

**Comment by arizonal2014** [comment]
Again Thank you very much. I appreciate. I have fixed it. I converted my WordPress instance to headless CMS and then consumed the returned hits from Algolia.
