### ISSUE TITLE
This plugin is not properly prepared for localization with Polyglots/WordPress.org system

### ISSUE THREAD

**Issue by mihdan** [WebDevStudios/wp-search-with-algolia#3]
**To Reproduce**
1. Go to [link](https://translate.wordpress.org/locale/ru/default/wp-plugins/wp-search-with-algolia/)
2. See error

**Comment by twocs** [comment]
Actually this plugin is prepared for localization. It is using translations, but the way they programmed it is just not being recognized by the scanner. 

There are 60 strings that are ready for Russian translations. https://translate.wordpress.org/projects/wp-plugins/wp-search-with-algolia/dev-readme/ru/default/?filters%5Bstatus%5D=untranslated

Also the search results have nothing to do with translations. The translations only apply to the admin area. More details here:
https://community.algolia.com/wordpress/internationalization.html

**Comment by twocs** [comment]
I'm thinking that the error is just due to the text domain not matching the folder name. 
https://github.com/WebDevStudios/wp-search-with-algolia/pull/5
