### ISSUE TITLE
Why 7.2 requirement?

### ISSUE THREAD

**Issue by sgatz** [WebDevStudios/wp-search-with-algolia#30]
Is there anything in the code that requires PHP 7.2?  I've got a set of servers (load balanced) all on 7.1 and don't have near term plans to upgrade.  Usually, plugins try to require the lowest version of PHP that they can possibly without breaking stuff.   Is there a way you can knock it down?

**Comment by gregrickaby** [comment]
Hey @sgatz 

Thank you for using our plugin and the feedback. I can appreciate your concern. It's not easy managing servers, let alone a set of load balancers too! I've only dabbled with a load balancer configurations in the past, and well, walked away feeling in over my head... so kudos!

I don't know if you're aware, but PHP 7.1's end of life was December 2018. I also just read PHP 7.1 will no [longer receive security updates](https://www.php.net/supported-versions.php) as of December 1, 2019. (that's 14 days from now) PHP 7.3 however, will be supported until December 2021.

PHP versions are moving fast and to keep pace WordPress just bumped their [minimum version](https://wordpress.org/about/requirements/) to PHP 7.3. We're working on a [major update](https://github.com/WebDevStudios/wp-search-with-algolia/milestone/2) coming in December, and this new version will also require a minimum of PHP 7.3.

I get it, upgrades are never fun...especially when there are complex configurations involved! But you may want reconsider your plans to stay on PHP 7.1. If there's anything WebDevStudios can do to help? Let us know.

Cheers! 🍻

**Comment by sgatz** [comment]
Thanks for the note and info. Yes of course I should move, but the thing I like about WordPress is they updated their “recommended version” not their “minimum version” so I can use WordPress uninterrupted until I make the switch.  Now with your plugin I’m forced to stay on an older version until I switch.  

It sounds like I can’t convince you, but I’d love to benefit from your upgrades in the interim.

And yes, I’ll calendar our upgrade to 7.3

—Scott

**Comment by richaber** [comment]
@sgatz since PHP 7.1 stopped receiving security support as of [December 1st]((https://www.php.net/eol.php)), I'm closing this ticket.
