### ISSUE TITLE
Question: Utility method to index individual post (when save_post) is not used

### ISSUE THREAD

**Issue by aaronware** [WebDevStudios/wp-search-with-algolia#301]
Within a custom implementation with woocommerce we utilize the Woo CRUD methods to update product data such as price and inventory for products. When we run our Warehouse/ERP sync once it is finished we reindex all the data which is pretty straightforward. However, there are times were an admin/store manager can sync an individual product w/ the ERP system. In that scenario we want to fire off a sync of that product similar to how you are tying into save_post.

What's the most efficient way to instantiate the Algolia_Posts_Index w/ all the proper configuration it needs to sync the individual post? I see when the save_post hook happens, it instantiates the index but also ties into a few other areas. I figured I would ask before I go down the rabbit hole as there may already be something in place that I am not seeing.

I know you don't specifically support any specific Ecomm plugin per se, so generally speaking, this is more so. How can I index a post that is updated when save_post isn't the mechanism used for saving the content?

**Comment by tw2113** [comment]
While this specific case isn't one that will be initially covered, I am able to say that we are going into more ecommerce centric focused addons around Algolia, but it is not going to be a free addon.

That said, I know for some WooCommerce customization, I managed to wire up listening to order completed actions, and updating products based on that. The code can be seen below, and hopefully that provides some ideas for your specific use case.

```
<?php
function algolia_update_total_sales_on_completed( int $order_id ) {
	$order       = wc_get_order( $order_id );
	$order_items = $order->get_items();

	$searchable_post_types = get_post_types(
		[
			'exclude_from_search' => false,
		],
	);
	$indices[]             = new \Algolia_Searchable_Posts_Index( $searchable_post_types );

	$algolia_plugin     = \Algolia_Plugin_Factory::create();
	$synced_indices_ids = $algolia_plugin->get_settings()->get_synced_indices_ids();
	$index_name_prefix  = $algolia_plugin->get_settings()->get_index_name_prefix();
	$client             = $algolia_plugin->get_api()->get_client();

	// Only include Autocomplete index if enabled.
	if ( in_array( 'posts_product', $synced_indices_ids, true ) ) {
		$indices[] = new \Algolia_Posts_Index( 'product' );
	}

	foreach ( $indices as $index ) {
		$index->set_name_prefix( $index_name_prefix );
		$index->set_client( $client );

		if ( in_array( $index->get_id(), $synced_indices_ids, true ) ) {
			$index->set_enabled( true );
		}
	}

	foreach ( $order_items as $item ) {
		$product_id = $item->get_product_id();
		$product    = get_post( $product_id );
		foreach ( $indices as $index ) {
			if ( ! $index->supports( $product ) ) {
				continue;
			}

			try {
				$index->sync( $product );
			} catch ( AlgoliaException $exception ) {
				error_log( $exception->getMessage() ); // phpcs:ignore -- Legacy.
			}
		}
	}
}
add_action( 'woocommerce_order_status_completed', 'algolia_update_total_sales_on_completed' );
```

**Comment by aaronware** [comment]
@tw2113 thanks, this is perfect
