### ISSUE TITLE
Upgrade to latest version for Instantsearch 4.x

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#318]
Presently at 4.54.1. We're on version 4.46.2 which is from September 2022

**Comment by coreyworrell** [comment]
4.55.0 was just released, and features an `insights` option that will make click events and insights much easier to use. Any idea when this version will be included with the plugin?

https://github.com/algolia/instantsearch/releases/tag/instantsearch.js%404.55.0

**Comment by tw2113** [comment]
We don't have any formalized timelines for when this will happen at the moment.

We need to make sure we're having solid templates out of box for such things, for multiple users, which makes it a bit more difficult than if each person had their own copies of templates.

**Comment by coreyworrell** [comment]
@tw2113 The specific features I was mentioning would not affect any out-of-the-box templating or anything. But it would allow users like us to customize the template and more easily enable insights.

**Comment by tw2113** [comment]
We'd still need to test things out and make sure we're not breaking anything, and I'd prefer to err on the side of caution at the moment.

That said, we are intending to stay on more active overall development of WP Search with Algolia as well as the newly released Pro version. The InstantSearch upgrade isn't something we'd wall off into the pro plugin, so no need to potentially worry about that detail.

**Comment by tw2113** [comment]
Closing this as it looks like our merge of #341 handled.
