### ISSUE TITLE
"Question about plugin performance: Can it support searching 10 million blog posts?"

### ISSUE THREAD

**Issue by nevertoday** [WebDevStudios/wp-search-with-algolia#325]
I am wondering if their plugin is able to support the search of 10 million blog posts, as I have heard that their current version may not be able to handle this amount of data.

**Comment by tw2113** [comment]
Indexing in bulk would be a labor, for sure. I haven't tested out at that volume, but theoretically it should be able with enough time. Beyond the bulk indexing, it will index and update on post save, and that's one at a time with that.

Closing as a non-issue, but feel free to ask more questions if needed.
