### ISSUE TITLE
Delete -> Update operations running in the wrong order

### ISSUE THREAD

**Issue by colis** [WebDevStudios/wp-search-with-algolia#327]
**Describe the bug**
I'm using a custom Watcher class that listens for changes to the WordPress posts received from a webhook (API endpoint). The watcher is 99% identical to the one originally provided in the plugin, it just needed to be hooked to a different action instead of the `save_post` one.

I've recently come across a strange issue where existing posts in WordPress - and correctly synced to Algolia - were being deleted from the index after an update request. This is probably due to the plugin's logic for updating existing posts, that [deletes a post before updating it](https://github.com/WebDevStudios/wp-search-with-algolia/blob/4c002a7f1917603fb3a2a360ac325af08b65b0e2/includes/indices/class-algolia-posts-index.php#L393). It looks like, under certain circumstances (most likely due to a high number of concurrent requests), and due to the [asynchronous nature of write operations](https://www.algolia.com/doc/api-reference/api-methods/wait-task/#about-this-method), the delete operation is executed **after** the update operation (wrong order), which obviously removes the post from the Algolia index.

We reached out to the Algolia support team and they suggested implementing the [wait method](https://www.algolia.com/doc/api-reference/api-methods/wait-task/?client=php) for delete requests.

For my project I've created a custom index class - which is an almost exact copy of the original `Algolia_Posts_Index` class (I could not extend it due to it being declared final in the plugin) - with the exception of the `->wait()` method called right after the `deleteObjects()` method, which makes the delete operation synchronous, e.g.

```
if ( ! empty( $object_ids ) ) {
	$this->get_index()->deleteObjects( $object_ids )->wait();
}
```

This should prevent write operations from running in the wrong order when the server is under heavy load.

I'm happy to open a PR if you think that this can be a valid addition to the codebase.

**To Reproduce**
1. Send a high number of update requests to Algolia
2. After some time, the number of posts indexed on Algolia will decrease and will be less than the number of posts in WordPress

**Expected behavior**
1. The number of posts should always be in sync between WordPress and Algolia.
2. The update request flow should always be `delete operation → wait for the delete operation to complete → update operation`

**Comment by colis** [comment]
Hi @tw2113,

I've just created a PR https://github.com/WebDevStudios/wp-search-with-algolia/pull/328

The custom watcher is almost identical, these are the differences:

```
public function watch() {
	// Fires once a post has been received from the webhook and saved.
	add_action( 'save_post_from_webhook', [ $this, 'sync_item_from_webhook' ] );
}
```

```
/**
 * Sync item from the Connector webhook.
 *
 * @param int $post_id The post ID to sync.
 */
public function sync_item_from_webhook( $post_id ) {
	if ( in_array( $post_id, $this->posts_deleted, true ) ) {
		return;
	}

	$post = get_post( (int) $post_id );
	if ( ! $post || ! $this->index->supports( $post ) ) {
		return;
	}

	try {
		$this->index->sync( $post );
	} catch ( AlgoliaException $exception ) {
		error_log( $exception->getMessage() ); // phpcs:ignore -- Legacy.
	}
}
```

```
/**
 * Sync item.
 *
 * @param int $post_id The post ID to sync.
 *
 * @return void
 */
public function sync_item( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
		return;
	}

	if ( in_array( $post_id, $this->posts_deleted, true ) ) {
		return;
	}

	// Bail early if the request is coming from the webhook.
	if ( defined( 'WEBHOOK_REQUEST' ) && WEBHOOK_REQUEST ) {
		return;
	}

	$post = get_post( (int) $post_id );
	if ( ! $post || ! $this->index->supports( $post ) ) {
		return;
	}

	try {
		$this->index->sync( $post );
	} catch ( AlgoliaException $exception ) {
		error_log( $exception->getMessage() ); // phpcs:ignore -- Legacy.
	}
}
```

**Comment by tw2113** [comment]
See https://github.com/WebDevStudios/wp-search-with-algolia/pull/328
