### ISSUE TITLE
Better way to translate strings

### ISSUE THREAD

**Issue by espenlg** [WebDevStudios/wp-search-with-algolia#35]
I wanted to translate the string "results found in [..]ms" and I solved it by editing `instantsearch-preact.min.js` directly but I feel it's a very hacky way of doing it.

It would be nice to be able to translate the strings displayed on the client side without risking it being overwritten in the next update.

**Comment by tw2113** [comment]
Looks like we'll need to find a way to properly internationalize this spot below for that. We'll also need to check and see if these files are part of a build setup right now as they look like they're already webkit compiled as is.

```
{{#hasNoResults}}No results{{/hasNoResults}}\n  {{#hasOneResult}}1 result{{/hasOneResult}}\n  {{#hasManyResults}}{{#helpers.formatNumber}}{{nbHits}}{{/helpers.formatNumber}} results{{/hasManyResults}}\n  <span class="{{cssClasses.time}}">found in {{processingTimeMS}}ms</span>
```

**Comment by richaber** [comment]
Howdy @espenlg,

After thinking about this and looking into it a bit, I've determined that you do not need to edit the JS file directly.

If you haven't already done so, copy the `wp-content/plugins/wp-search-with-algolia/templates` directory into your own theme, and rename it to `algolia`.

If your theme is named mytheme, then the folder should look like: wp-content/themes/mytheme/algolia.

You can then edit the algolia/instantsearch.php file in your theme to customize the templating string used by instantsearch stats widget.

I tested _this snippet_ locally:

```
/* Stats widget */
search.addWidget(
	instantsearch.widgets.stats({
		container: '#algolia-stats',
		templates: {
			body: function(data) {
				return '<div>' + data.nbHits + ' resultater funnet i ' + data.processingTimeMS +'ms.</div>'
			},
		},
	})
);
```

And here's the result:

![Screen Shot 2019-12-06 at 7 25 07 PM](https://user-images.githubusercontent.com/5407441/70366606-27af1700-185e-11ea-817c-5ec44e5f237f.png)

**Comment by espenlg** [comment]
@richaber Fantastic! Works like a charm! I've already copied `instantsearch.php` to `wp-content/themes/mytheme/` and it works fine too. Good thing having it in an algolia subfolder though. Keeps it tidy and I'll do that.
Thank you again!
