### ISSUE TITLE
Question: Possible to search multiple WP Sites

### ISSUE THREAD

**Issue by shanerobinson** [WebDevStudios/wp-search-with-algolia#352]
**Is your feature request related to a problem? Please describe.**
I used Algolia many years ago with and an ExpressionEngine site that was only updated a couple times a month. So all I did was export a CSV from EE and replace the existing index on Algolia. So that's the extension of my Algolia use. 

**Describe the solution you'd like**
I have a client who owns 3 websites. Let's call them Site1, Site2, Site3. When people search on Site2, they would like WP post results from all 3 sites. 

**Describe alternatives you've considered**
I know this is probably too simple... And I don't currently have access to their WP to test. But what would happen if the plugin was installed on all 3 sites and the same API Keys were used on all 3 WP sites? Wouldn't all 3 WP sites update the same index?

If it's not this simple, is there a way to do this?

**Comment by tw2113** [comment]
Hi @shanerobinson 

Technically, you could do that and have all the same application IDs and prefixes and whatnot, but the biggest issue there is going to be object ID uniqueness. For example, out of box, all sites get a "Sample Page" and that's always post ID 2. If you were to push 3 sites into 1 index, whichever got indexed last, would be what shows up in Algolia for object ID 2. Not ideal.

That said, I know with version 1.3.0 of our Algolia Pro addon, it's biggest feature is pushing multiple sites from a Multisite, into 1 index and allowing to search all the content from all 3, with the object ID part handled already. However, I'm not sure if the 3 sites you mention are separate single sites, or potentially 3 in a multisite, so this may not be a best fit for you either.

**Comment by tw2113** [comment]
Closing this issue as we have functionality like this in our WP Search with Algolia Pro version 1.3.0. We have content scheduled to be published soon with more information about the process and implementation.

**Comment by shanerobinson** [comment]
Thanks so much! This just resurfaced in our ClickUp and we'll take a look at the Pro 1.3.0 version.
