### ISSUE TITLE
FSE compatible template files

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#355]
What can we do to help make sure our template files is Full Site Editing compatible?

For the instantsearch.php file, we have `get_header()` and `get_footer()` calls, but also some internationalized Algolia widget titles that make use of PHP calls.

For the autocomplete.php, mostly just internationalization. 

I think this could be easy-ish, but I am making no guarantees on that.

**Comment by tw2113** [comment]
Extra thoughts: this probably won't be a case of modifying the existing PHP files, but making FSE compatible equivalents that we could perhaps ship with the plugin alongside the current PHP versions.

**Comment by peiche** [comment]
Isn't this the same as [this issue](https://github.com/WebDevStudios/wp-search-with-algolia/issues/216)?

**Comment by tw2113** [comment]
@peiche yes, forgive me for forgetting about that ticket from you. I will get these merged in a sense.

**Comment by tw2113** [comment]
Closing in favor of #216
