### ISSUE TITLE
Filter typo in Wiki

### ISSUE THREAD

**Issue by hereswhatidid** [WebDevStudios/wp-search-with-algolia#356]
In the [Code References -> Filter Hooks](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Filter-Hooks) section of the WIKI there is a reference to:

`algolia_post_image_sizes`

It should actually be:

`algolia_post_images_sizes`

**Comment by tw2113** [comment]
Thanks for that @hereswhatidid 

Fixed and should be good now with the wiki page.
