### ISSUE TITLE
Algoliasearch-woocommerce

### ISSUE THREAD

**Issue by omnisity** [WebDevStudios/wp-search-with-algolia#36]
Thanks for taking over the port of Algolia Search, we use this on our WooCommerce site. Are there plans to take over the algoliasearch-woocommerce archive?

https://github.com/algolia/algoliasearch-woocommerce

We have this installed, but we can't use your plugin because we get error messages:

Algolia Search for WooCommerce: Search by Algolia – Instant & Relevant results plugin should be enabled. (your version is)

and

Algolia Search for WooCommerce: Search by Algolia – Instant & Relevant should be updated to at least version 2.1.0.

If we enable the original plugin by Algolia Version 2.11.3 the Search for WooCommerce message is removed but we still get:

Algolia Search for WooCommerce: Search by Algolia – Instant & Relevant results plugin should be enabled.

**Comment by richaber** [comment]
Howdy @omnisity, I am not aware of any plans to fork the WooCommerce add-on at this time.

**Comment by andrewlreeve** [comment]
@omnisity we're looking to update the dependencies in the https://github.com/algolia/algoliasearch-woocommerce plugin to support this fork. When we do, I share a copy for you.
