### ISSUE TITLE
Consideration: Update `remove_content_noise` static method to use `wp_kses_post()`

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#360]
Current method body:

```
public static function remove_content_noise( $content ) {
	$noise_patterns = array(
		// strip out comments.
		"'<!--(.*?)-->'is",
		// strip out cdata.
		"'<!\[CDATA\[(.*?)\]\]>'is",
		// Per sourceforge http://sourceforge.net/tracker/?func=detail&aid=2949097&group_id=218559&atid=1044037
		// Script tags removal now preceeds style tag removal.
		// strip out <script> tags.
		"'<\s*script[^>]*[^/]>(.*?)<\s*/\s*script\s*>'is",
		"'<\s*script\s*>(.*?)<\s*/\s*script\s*>'is",
		// strip out <style> tags.
		"'<\s*style[^>]*[^/]>(.*?)<\s*/\s*style\s*>'is",
		"'<\s*style\s*>(.*?)<\s*/\s*style\s*>'is",
		// strip out preformatted tags.
		"'<\s*(?:code)[^>]*>(.*?)<\s*/\s*(?:code)\s*>'is",
		// strip out <pre> tags.
		"'<\s*pre[^>]*[^/]>(.*?)<\s*/\s*pre\s*>'is",
		"'<\s*pre\s*>(.*?)<\s*/\s*pre\s*>'is",
	);

	// If there is ET builder (Divi), remove shortcodes.
	if ( function_exists( 'et_pb_is_pagebuilder_used' ) ) {
		$noise_patterns[] = '/\[\/?et_pb.*?\]/';
	}

	$noise_patterns = (array) apply_filters( 'algolia_strip_patterns', $noise_patterns );

	foreach ( $noise_patterns as $pattern ) {
		$content = preg_replace( $pattern, '', $content );
	}

	$content = str_replace( '&nbsp;', ' ', $content );

	return html_entity_decode( $content );
}
```

How much of this could we update, without badly affecting current users, with a change to `wp_kses_post()` instead?

Should we consider leaving this method alone and create a new method that we start using internally, with `wp_kses_post()`.

We could attempt to deprecate it as well.

**Comment by tw2113** [comment]
Couple notes.

Seems to do nothing, or at least I haven't found a pattern that would match it:
```
"'<\s*pre[^>]*[^/]>(.*?)<\s*/\s*pre\s*>'is",
```

Strips everything:
```
"'<\s*pre\s*>(.*?)<\s*/\s*pre\s*>'is",
```

Both seem to have un-escaped delimiters at least according to https://regex101.com/. This would be the `/` meant to mark the closing pre tag.

Based on what I can find with github archive history, these two lines were added outright as is, in https://github.com/algolia/algoliasearch-wordpress/commit/da9625a16f150f1316d16cd299b2d74d123e32a9 and no one has touched it since.

**Comment by tw2113** [comment]
@asharirfan the more I think about it, the more I feel this one may be a "for a small user base" issue, rather than one that's for sure going to benefit the greater overall user base.

**Comment by asharirfan** [comment]
@tw2113 Agreed! Also, I don't see the point of this function except maybe to remove comments and cdata. Every other pattern is a HTML tag.

Right after `remove_content_noise` is called, the content is passed through [wp_strip_all_tags](https://developer.wordpress.org/reference/functions/wp_strip_all_tags) function. This function literally strips all the html tags from the content.

```
public static function prepare_content( $content ) {
	$content = self::remove_content_noise( $content );
	return wp_strip_all_tags( $content );
}
```

**Comment by tw2113** [comment]
I wonder if we added that or if that was Algolia originally. I'll have to dig in to that later, before making decisions on closing or not.

**Comment by asharirfan** [comment]
Here is the history of the file `class-algolia-utils.php`: https://github.com/algolia/algoliasearch-wordpress/commits/master/includes/class-algolia-utils.php

And here is the commit that added the `remove_content_noise` function: https://github.com/algolia/algoliasearch-wordpress/commit/3925e219bf244413c261eab3ea7f2314099dac81

**Comment by tw2113** [comment]
They added `strip_tags()` and then we changed to `wp_strip_all_tags()` in https://github.com/WebDevStudios/wp-search-with-algolia/commit/6790c5ad6463ba90538f5f5c3c4c3e3de9cb3805

**Comment by tw2113** [comment]
I'm wondering if they did both to help ease up with finding tags?

Anyways, for the sake of backwards compatibility at the moment, I'm going to go with wontfix right now. If we decide we want to refactor it somehow in the future, we can. Perhaps in 3.x release or other future backwards compat breaking release.
