### ISSUE TITLE
Instancesearch hits are wrong

### ISSUE THREAD

**Issue by ZahidHasan107** [WebDevStudios/wp-search-with-algolia#378]
In my woo-commerce site autocomplete working fine but instancesearch hits are not proper response .
![Screenshot(27)](https://github.com/WebDevStudios/wp-search-with-algolia/assets/50963920/0d8b60b8-6267-4496-b876-30b5a8a1d710)

**Comment by tw2113** [comment]
Have you done indexing for the "Search Page" settings? By default, autocomplete and instantsearch use different indexes, unless your autocomplete is set to "All Posts".

**Comment by ZahidHasan107** [comment]
Is it possible to use same indexes for autocomplete and instantsearch without set all posts.

**Comment by tw2113** [comment]
Not really, no. 

Still feels like you don't have any content in the searchable_posts index yet, but it does feel like you have autocomplete generally configured to your liking.

**Comment by tw2113** [comment]
Just checking in once more @ZahidHasan107

**Comment by tw2113** [comment]
Closing as a non-issue at the the moment. If/when the original reporter returns to it, we can resume troubleshooting at that time.
