### ISSUE TITLE
How to use integrate instantsearch functionalities in wordpresss default UI 

### ISSUE THREAD

**Issue by abdulkadernsu** [WebDevStudios/wp-search-with-algolia#386]
This is my woocommerce site: https://pemamall.com/ 
Currently using algolia to show search suggestion. Now want to use algolia to show result page as well. I don't like instant search UI. I want to keep the default UI of my site but it should work with algolia functionalities. 
Is there any scope? 

Thanks

**Comment by tw2113** [comment]
@abdulkadernsu This setting would have queries sent to Algolia, and then Algolia will return the post ID objects as part of `pre_get_posts` `post__in` parameter that your site can then fetch to show your customers.

<img width="1091" alt="Screen Shot 2023-10-31 at 3 18 23 PM" src="https://github.com/WebDevStudios/wp-search-with-algolia/assets/484075/57f15f34-3f9d-426b-9a9f-c96c52fc378c">

You won't get things like the Algolia facets and widgets with this, but you'd get the search in general powered by Algolia.

Closing this issue as a general support, but feel free to respond as needed.

**Comment by abdulkadernsu** [comment]
Use Algolia with native.... doesn't show the all products. Even I indexed all the products & tags. 
What might be the solution?

**Comment by tw2113** [comment]
This setting option isn't going to influence any initial states with the display of your products. It's just going to intercept the search query and return IDs for which items it feels meets best results, based on your index configurations with the `wp_searchable_posts` index.

To be certain, your product totals in your WP dashboard are matching up with what you're seeing in your algolia.com dashboard?

Are you trying the same query in both places and comparing the results?
