### ISSUE TITLE
Invalid Application-ID or API key 

### ISSUE THREAD

**Issue by rblackfox** [WebDevStudios/wp-search-with-algolia#399]
**Describe the bug**
Testing out the plugin and we cannot connect to Algolia.
Admin API field is greyed out and cannot be inputed:

**To Reproduce**
1. Install & Activate Plugin
2. Enter Application ID, Search Only API-key 
3. Try to Enter Admin API Key but cannot because field is greyed out. Click save.
4. Receive Error: "Invalid Application-ID or API key"
5. What next? Why can't we enter an Amin API key??

**Expected behavior**
Be able to enter Admin API keys and connect to Algolia so we can test the plugin. 

**Screenshots**
<img width="739" alt="Screen Shot 2024-02-19 at 2 47 17 PM" src="https://github.com/WebDevStudios/wp-search-with-algolia/assets/7915930/19ff9858-ad5b-45aa-ba17-043c2321d5db">

**Comment by tw2113** [comment]
If you have grayed out inputs, then there's a good chance you have some of our constants defined somewhere, probably your `wp-config.php` file.

You can see all our constants at https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Constants#constants-reference

**Comment by rblackfox** [comment]
It was the Algolia WooCommerce Indexer Plugin interfering.
Fixed. Thanks for the assistance \m/

**Comment by tw2113** [comment]
Glad we got it figured out and tracked down.

I know WP Search with Algolia is very much a fork of Algolia's own plugin from years ago that they abandoned, so I could definitely see similar codebases and possibly similar configs running into each other like this.
