### ISSUE TITLE
Indexing large records

### ISSUE THREAD

**Issue by sebastianthulin** [WebDevStudios/wp-search-with-algolia#41]
**Is your feature request related to a problem? Please describe.**
A common issue with Algolia is that the record can grow to large to be indexed. Algolia will respond with a "fatal" error not continuing to index the rest of current batch.  Having a record exceeding a certian limit is therefore a critical issue. 

Plan limitations: https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/

**Describe the solution you'd like**
Solution examples: https://www.algolia.com/doc/integration/wordpress/advanced/splitting-records/?language=php

**Describe alternatives you've considered**
No alternatives than implementing fixes to comply with above linked documentation. 

**Additional context**
Unshure where to implement this feature best. Have found the "buildBatch" function in /src/AlgoliaSearch/Index.php to be a good candidate. This might increase number of indexing "slots" used to create a index entry. It may also require some settings to be made regarding the unique key setting in algolia.

**Comment by richaber** [comment]
Howdy @sebastianthulin.

There is some pre-existing [record splitting](https://community.algolia.com/wordpress/frequently-asked-questions.html#i-have-more-records-than-i-have-posts-is-that-normal-) of posts in the [`Algolia_Posts_Index::get_post_records()`](https://github.com/WebDevStudios/wp-search-with-algolia/blob/master/includes/indices/class-algolia-posts-index.php#L100) and [`Algolia_Searchable_Posts_Index::get_post_records()`](https://github.com/WebDevStudios/wp-search-with-algolia/blob/master/includes/indices/class-algolia-searchable-posts-index.php#L90) methods.

Is that existing functionality around record splitting not behaving as expected? Can you take a look at and see if that's related to the issue you are experiencing? Perhaps that code needs refining?

**Comment by claytoncollie** [comment]
@sebastianthulin I know this is closed and a bit late. I was going through each issue to see what is going on in this repo.

This plugin has built-in splitting if the post_content grows too large. if you add your own key-value pairs to the object, they are not taken into account for the size of the object. For my sites, we opted to append our content to the end of the post_content object so that it would show up in the hits and then if we need to display any data in our template, that is the only time we use custom key-value pairs.

**Comment by sebastianthulin** [comment]
Hi! Thank you for the reply. Ended up writing my own plugin after all for our Indexing needs. 

Dosen’t solove this any better than your plugin, but has some nice features like checking if a post needs updates before sending a update action. 

Might provide some ideas for future implementations. 


https://github.com/helsingborg-stad/algolia-index

https://github.com/helsingborg-stad/algolia-index-modularity-addon/

https://github.com/helsingborg-stad/algolia-index-js-searchpage-addon
