### ISSUE TITLE
Hierarchical menu widget with custom taxonomies

### ISSUE THREAD

**Issue by fabien-morvan** [WebDevStudios/wp-search-with-algolia#42]
**Describe the bug**
Getting no results after choosing the second level of the hierarchical menu

**To Reproduce**
Create two custom taxonomies and make the hierarchical menu out of them.
There won't be any results

**Expected behavior**
Display results

**Additional context**
The bug was already in the previous version of the plugin.

**Comment by richaber** [comment]
Howdy @fabien-morvan, I'm not sure I fully understand the issue described. Could you provide more details so that I could reproduce the issue and test it?

**Comment by fabien-morvan** [comment]
1/ I created a custom taxonomie on WP with 2 levels
2/ I added the facets on Algolia and everything is working fine with the first level.
3/ When I add the 2nd level, the 1st one is still working but the 2nd one always return an empty result.

Here is the widget I used:
`search.addWidget(
	instantsearch.widgets.hierarchicalMenu({
		container: '#facet-formation',
		attributes: ['formation.category.lvl0.name','formation.category.lvl1.name'],
		templates: {
			header: '<h3 class="widgettitle">Formation</h3>'
		}
	})
);`

It's almost the same issue as this one:
https://github.com/algolia/algoliasearch-wordpress/issues/806

**Comment by tw2113** [comment]
Closing as a non-issue at the moment.
