### ISSUE TITLE
No highlighting in search results

### ISSUE THREAD

**Issue by mrfsrf** [WebDevStudios/wp-search-with-algolia#421]
**Describe the bug**
For some reason i dont have search highlight on results.
Tried to error log inside `class-algolia-search.php` inside method `pre_get_posts`
```php
		try {
			$results = $this->index->search( $query->query['s'], $params, $order_by, $order );
			error_log('Algolia search results: ' . print_r($results, true));

		} 
```
inside the debug.log there is: `[_highlightResult] => Array`.
Also made sure that highlightning is enabled
```php
	private function highlighting_enabled() : bool {
		$enabled = apply_filters( 'algolia_search_highlighting_enabled', true );
    error_log('Highlighting enabled: ' . var_export($enabled, true));
    return $enabled;
		// return apply_filters( 'algolia_search_highlighting_enabled', true );
	}
```
which is true.
Do i miss something?	

Im using **Use Algolia with the native WordPress search template** as an option

**Comment by tw2113** [comment]
Can you verify whether or not you have this small script block being output in the `<head>` of your search results page?

```
<style>
	.algolia-search-highlight {
		background-color: #fffbcc;
		border-radius: 2px;
		font-style: normal;
	}
</style>
```

Also worth checking/confirming the Highlighting section of your index's configuration. If you've set anything specific for highlighting, you'd want to add in `post_title`, and `post_excerpt`. If you haven't customized that spot, then it should be applying to all searchable attributes of which, both of these are out of box with the plugin.

**Comment by mrfsrf** [comment]
yup. the algolia-search-highlight css class is in the head.
Second part i dont fully understand. Do you mean this?
<img width="1120" alt="Screenshot 2024-06-20 at 19 55 37" src="https://github.com/WebDevStudios/wp-search-with-algolia/assets/13692133/6490bcb7-963b-40f5-98ec-524da0b9f57a">

**Comment by tw2113** [comment]
Specifically the "UI Demos" around the top middle space in the image. If you're not using that "UI Demos" part, then I'm not quite sure which Display Preferences you're referring to.

Also make sure you're working with the `wp_searchable_posts` index, with whatever prefix you chose, as that's going to be the index used for with Native Search template.

**Comment by mrfsrf** [comment]
<img width="1334" alt="Screenshot 2024-06-20 at 21 30 09" src="https://github.com/WebDevStudios/wp-search-with-algolia/assets/13692133/4d269a6f-7e90-4313-a063-4a915c66b471">
<img width="402" alt="Screenshot 2024-06-20 at 21 29 56" src="https://github.com/WebDevStudios/wp-search-with-algolia/assets/13692133/f0c5d99c-131c-4593-bb5c-ea4b08cb59fa">

I created the UI demo and those are the results.
What im baffled about is that method `highlight_the_title` (inside `Algolia_Search` class) for example is not logging out
```php
	public function highlight_the_title( $title, $post_id ) {
		error_log("Highlighting title for post ID: $post_id");

		$highlighted_title = $this->current_page_hits[ $post_id ]['_highlightResult']['post_title']['value'] ?? null;

		if ( ! empty( $highlighted_title ) ) {
			$title = $highlighted_title;
		}

		return $title;
	}
```

**Comment by tw2113** [comment]
I'd be able to troubleshoot a lot better with a link to the live page where the issue is happening, as opposed to their UI Demos area. The demo area is not where the issue is.

The `highlight_the_title()` method should be getting called on the `the_title` filter, so if you're not using that in your theme, that may be why that one is failing.

Just to be certain, this spot on the right of the screenshot, for your index, is empty, correct?
<img width="971" alt="Screen Shot 2024-06-20 at 3 05 44 PM" src="https://github.com/WebDevStudios/wp-search-with-algolia/assets/484075/1427fda5-1e86-418a-b65c-707015abc05e">

If empty, then as the text says, all searchable attributes should be getting the highlight treatment.

**Comment by mrfsrf** [comment]
Thanks! Manged to solved it. Had to call correct filters on title and excerpt
