### ISSUE TITLE
Automatic Sync Issues

### ISSUE THREAD

**Issue by GeronimoJohn** [WebDevStudios/wp-search-with-algolia#429]
Such a great plugin! Thank you guys for the hard work put into this. This might be more of a question rather than an issue. Do direct me in the direction of where to put this in if a question

**Describe the bug**
We manually indexed several custom post types to Algolia, excluding blogs. After adding blogs to these indices, we expected them to sync automatically, but they weren't added to Algolia

Manually indexed meaning I've clicked on the re-index button for my desired indices

**To Reproduce**

1. Create or update any article (e.g. the title).
2. Changes are not reflected on the Algolia dashboard.

**Expected behavior**
We expected blogs to sync automatically to their indices upon creation or update, but they weren't added

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Additional context**
Initially, Search results was set to `Do not use Algolia`. 

Found this [thread](https://github.com/WebDevStudios/wp-search-with-algolia/issues/83) having mixed suggestions that don't use it as it doesn't work for automated sync and some mentions that it doesn't matter.

So updated it to be `Use Algolia with the native WordPress search template`. Created blog and published. Still no luck

Found the wiki as well about [Automated sync](https://github.com/WebDevStudios/wp-search-with-algolia/wiki/Automated-Sync). It states: `By default, this plugin will ensure that your WordPress content that is flagged for indexing stays in sync with Algolia`. I guess my question is how to set an index as flagged for automated sync?

**Steps taken**

1. Install the Plugin
2. Added the API ID, Keys, etc...
3. Created the post types (no blogs at initial creation)
4. Navigated to Search Page and chose `Do not use Algolia`
5. Navigated to Autocomplete and clicked on `re-index` for desired indices
6. Created a blog and published (didn't sync)
7. Change Search Page setting to be `Use Algolia with the native WordPress search template`
8. Created a blog and published (still didn't sync)

**Comment by tw2113** [comment]
Good day @GeronimoJohn 

Based on what I'm seeing with some testing and trial/error, the "re-index" buttons are pushing up your content regardless of general WP Search with Algolia status. However, once you want to get things auto-sync'ing as you update/add individual pieces of content, you need to have things configured a bit more.

For example, I created a "movie" post type, and once I checked the checkbox next to it in my Autocomplete settings page and saved the changes, at that point it was auto-sending to Algolia, even though I didn't have "Enable Autocomplete" checked at the top.

So the bulk reindex buttons are kind of a hammer to just push everything, but once you get granular, it needs configured settings.

As extra detail, the plugin creates separate indexes, depending on chosen settings. For example, in Autocomplete, if you choose "All Posts" at the very top, and then also turn on one of the two Search Page options, both the Autocomplete and the Search page would share the `wp_searchable_posts` index. However, with Autocomplete, if you choose any of the individual post types, terms, or users options, those all create their own separate index.

**Comment by GeronimoJohn** [comment]
@tw2113 that worked like a charm! Thanks for providing direction for my question. And yes the separate indexes is what we're after. Again thanks! Closing down this ticket
