### ISSUE TITLE
Instant Search only displaying # of results, not actual results

### ISSUE THREAD

**Issue by hernumber9** [WebDevStudios/wp-search-with-algolia#57]
**Describe the bug**
On the search page, as I type in a word, I see "x results found in y ms", but no results are shown below the search box
![Screen Shot 2020-04-02 at 7 27 39 PM](https://user-images.githubusercontent.com/63079218/78309131-2f36b200-7518-11ea-9a71-d1b860611a26.png)

There is also an error when I inspect the page (shown below)
![Screen Shot 2020-04-02 at 7 28 28 PM](https://user-images.githubusercontent.com/63079218/78309137-3493fc80-7518-11ea-9389-26749011596a.png)

**To Reproduce**
Type in any word in the search box

**Expected behavior**
Search results should be shown as I type

**Screenshots**

**Comment by hernumber9** [comment]
Just wanted to add, I believe this may be an issue with the theme I'm using (Avada).

**Comment by richaber** [comment]
Howdy @hernumber9.

Are you using WP Search with Algolia version 1.2.0 as downloaded from [WordPress.org](https://wordpress.org/plugins/wp-search-with-algolia/), or are you using a cloned copy of this repository (and if so, which branch)?

**Comment by hernumber9** [comment]
It was downloaded from WordPress.org

**Comment by richaber** [comment]
@hernumber9 is the site where this is occurring publicly accessible on the internet? If so, could you provide a link where I can see the error?

**Comment by hernumber9** [comment]
Here is the search page: https://supportbusinessdev.bot.com/?s=grant

**Comment by richaber** [comment]
Howdy @hernumber9 

I don't _think_ it's a conflict with the theme, though you could try enabling a different theme just for debugging (always get a DB backup first though).

It appears that the data object has an undefined `_snippetResult`, though I am uncertain why that might be.

This line `<# if ( data._snippetResult['content'] ) { #>` then triggers the error you're experiencing.

If you are a developer, you could copy the instantsearch.php template out of the plugin and into a child theme, where you could try to squash the bug.

I think changing this line:
`<# if ( data._snippetResult['content'] ) { #>`

To this:
`<# if ( undefined !== data._snippetResult && data._snippetResult[ 'content' ] ) { #>`
in a copy of instantsearch.php in your child theme _might_ do the trick.

**Comment by hernumber9** [comment]
Thanks, will give it a shot and let you know!

**Comment by hernumber9** [comment]
Trying to override the php file in my theme, but it's not picking it up. I've placed instantsearch.php in wp-content/themes/Avada/wp-search-with-algolia; is that correct or should it be in a different directory?

**Comment by richaber** [comment]
Howdy @hernumber9 

I would do this in a [child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/) of Avada, so that updates to the parent Avada theme don't overwrite your customization. However, if you're just testing for now, that's fine (but long term I would absolutely use a child theme).

So in your example above, the path should be
`wp-content/themes/Avada/algolia/instantsearch.php`

If in a child theme, something like
`wp-content/themes/avada-child-theme/algolia/instantsearch.php`

**Comment by hernumber9** [comment]
Thanks, renaming the directory to algolia did the trick. The fix you suggested also worked, so thanks for that as well. :)
