### ISSUE TITLE
Show results post types from 2 different sites (combined cross search)

### ISSUE THREAD

**Issue by moisb** [WebDevStudios/wp-search-with-algolia#61]
Hello. I have 2 wordpress sites:

**Site 1: I want to show 2 types of posts (post, coupon) and 4 taxonomies (category, post_tag, coupon_store, coupon_category)**

**Site 2 (woocommerce): I want to show 2 types of posts (post, product) and 4 taxonomies (category, post_tag, product_tag, product_cat)**

I want both sites with "wp-search-with-algolia" installed to show results from each other. Currently I can do this using the "WP Solr Pro" plugin, but it is slow, full of bugs, and the monthly cost is similar to the Algolia Starter plan.

when I try to do the same using the Algolia plugin, the indexes are not complementary, they are overwritten (I can only show results from 1 site)

PS> I am not a programmer, so anyone who can help with a ready-made solution, I am grateful.

**Comment by lazmo88** [comment]
Untested, but did you rename your indices differently per website by using the "Index name prefix" setting? If yes, single Algolia app should be able to receive data to multiple indices. After this, you should update your InstantSearch.js/Auto complete script to include multiple indices: https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/multi-index-search/js/

Give it a shot and let us know how it went :)

**Comment by moisb** [comment]
thank you @lazmo88 but I don't know how to do this. I didn't find any "InstantSearch.js" file. 
on "wp-content/plugins/wp-search-with-algolia/js/instantsearch.js/" has 2 files:
"instantsearch-preact.js" and "instantsearch-preact.min.js"

I don't know what or where to insert the code of the documentation you suggested.

**Comment by lazmo88** [comment]
@moisb you don't actually need to edit the bundled InstantSearch.js file at all, as you can just load it via CDN and then build your own custom InstantSearch.js UI. Kindly see following docs and examples.

https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/

https://www.algolia.com/doc/guides/building-search-ui/resources/demos/js/#e-commerce

**Comment by richaber** [comment]
Howdy @moisb, 

Unfortunately, we have no "ready-made solution" for this, as this is not a common use case.

@lazmo88 has provided some good information above about how you might be able to achieve your desired result. However, it would require some fairly heavy code customization, and you might want to consider enlisting a developer to help you.

**Comment by lukecav** [comment]
Also look at using `algolia_autocomplete_config` then defined the indexes.
https://discourse.algolia.com/t/using-multiple-indices-on-wordpress/2617/2
