### ISSUE TITLE
Trashed or Draft posts show up in index and results.

### ISSUE THREAD

**Issue by jondcampbell** [WebDevStudios/wp-search-with-algolia#64]
**Describe the bug**
When I move a post to trash or drafts it still shows up in search results.

**Expected behavior**
I would like those posts to be deindexed or at least have the post_status sent to Algolia so that search query can be modified to return only published posts.

**Comment by richaber** [comment]
Howdy @jondcampbell 

I am unable to reproduce the described issue.

To test, I created and published a Post, and the Post appeared in my Algolia Post Index. I then trashed the Post, and it was removed from my Algolia Post Index.

I then created and published another Post, and the Post appeared in my Algolia Post Index. I set that Post to Draft status, and it was removed from my Algolia Post Index.

For testing I used WP Search with Algolia 1.3.0, WordPress 5.4.2, and a default Twenty* theme.

Is it possible there could be some custom code modifying WP Search with Algolia's behavior? Or perhaps PHP code throwing errors that interferes with WP Search with Algolia's exptected functionality?

**Comment by richaber** [comment]
Howdy @jondcampbell I see you closed this. Can you share your findings?

**Comment by jondcampbell** [comment]
@richaber 
I was able to see that drafting and trashing would deindex posts when on my local.

Sometimes on our production the posts would not deindex, but I will assume that was either the post_status being cached or the API connection having an issue.

We have seen posts that are totally deleted from WP but exist in the Algolia index still (I have since manually deleted from index). I think the plugin is working as expected and if it doesn't sync right away we can probably "Save Draft" again to have it work the next time.

I'm chalking it up to "It's not you, it's me".

**Comment by richaber** [comment]
@jondcampbell Thank you for following up.
If you positively identify the source of the issue in the future, please add that information to this thread. It could prove useful if someone else runs into it.

**Comment by tw2113** [comment]
Based on what I'm seeing at https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/indices/class-algolia-searchable-posts-index.php#L422-L450 and https://github.com/WebDevStudios/wp-search-with-algolia/blob/main/includes/indices/class-algolia-posts-index.php#L438-L463 this is intended behavior in terms of the initial fetching. A post status of "any" for the WP_Query calls.

What is curious is going to be if somehow the "should index" logic is returning true. Both "should index" methods in the code is looking for the "publish" post status.
