### ISSUE TITLE
Workaround for using local-key

### ISSUE THREAD

**Issue by drzraf** [WebDevStudios/wp-search-with-algolia#66]
**Is your feature request related to a problem? Please describe.**
I would like to use a index-local key.
Sadly, local-key has can't use `getUserKeyACL`.

**Describe the solution you'd like**
A `getUserIndexKey($key, $index)` for `/1/indexes/%index%/keys/%key%` could be implemented and used has a fallback (or as a first-choice target) until the underlying library provide it.

**Describe alternatives you've considered**
[Updating the library](https://github.com/WebDevStudios/wp-search-with-algolia/issues/20) would definitely be a step forward, but won't help in this specific case since no method has been implement for this REST endpoint in v2.

**Additional context**
https://github.com/algolia/algoliasearch-client-php/issues/630

**Comment by richaber** [comment]
Howdy @drzraf.

I can find no reference documentation regarding Algolia "local keys", and I am unfamiliar with what that means in the context of Algolia.
Is there some documentation about Algolia "local keys" that you can refer me to?

Yes, we do (currently) rely on an older version of the Algolia PHP API Client.
Version 1.23.0 was the version in use by the official plugin when it was abandoned and we created our fork.

According to [this comment](https://github.com/algolia/algoliasearch-client-php/issues/630#issuecomment-646007266_) left on the issue your referenced:

> local keys are softly-deprecated, I'd recommend not using them. We remove this feature in v2. You can still call the endpoint manually but we'd rather not add a dedicated method.

If they are deprecated, and unsupported by the official library, I am reluctant to shim in support for a deprecated feature. It says they removed the feature in v2, but I see no reference to the feature in v 1.23.0.
