### ISSUE TITLE
is_valid_search_api_key too strict about broader permissions

### ISSUE THREAD

**Issue by drzraf** [WebDevStudios/wp-search-with-algolia#67]
**Describe the bug**
`is_valid_search_api_key` fails if the search-key has more than just `search`, `settings` & `listIndexes` permissions.

Still, for a sandbox key it's practical to use the same API key for both admin & search.
There should be a way to relax this check for test instances.
This is even more true in the case of [local key](https://github.com/WebDevStudios/wp-search-with-algolia/issues/66)

**To Reproduce**
1. Create a sandbox key
2. Use it for both ALGOLIA_SEARCH_API_KEY and ALGOLIA_API_KEY
3. Save setting
4. See error `It looks like your search API key is wrong. Ensure that the key you entered has only the search capability and nothing else. Also ensure that the key has no limited time validity.`

**Expected behavior**
If should work on WP development environments.

**Possible resolutions**
- In `is_valid_search_api_key`, I suggest to use:
`if ( ! empty( $scopes ) && (! defined(WP_ENV) || WP_ENV === 'production') ) {`
At least Bedrock WP installation provide this constant which could be 'test' ,'development' or 'production'.
- If local-key were supported, the check could be ignored for local keys
- Another approximative way could be to check whether index's prefix contains `test` or `dev` in its name.

**Comment by richaber** [comment]
Howdy @drzraf.

For my own clarification, are you saying that you want to use the "Admin API key" (which should be kept private) as the "Search-only API key" (which is publicly exposed)?

**Comment by drzraf** [comment]
Yes I wanted to do that (but on my local -test instance).

**Comment by richaber** [comment]
Howdy @drzraf 

I'm open to relaxing the `Algolia_API::is_valid_search_api_key()` method's permissions check for local development.

Since `WP_ENV` isn't nearly as ubiquitous outside of Bedrock, I would suggest that perhaps one of the more widely known/used constants such as `WP_LOCAL_DEV` or `WP_DEBUG` would make more sense to check against. Though I think `WP_LOCAL_DEV` makes more sense than `WP_DEBUG` and is less likely to be defined on a public facing install.

The method could be updated to something like this:

```
	public static function is_valid_search_api_key( $application_id, $search_api_key ) {
		$client = new Client( (string) $application_id, (string) $search_api_key );
		try {
			// If this call does not succeed, then the application_ID or API_key is/are wrong.
			$acl = $client->getApiKey( $search_api_key );

			// We expect a search only key for security reasons. Will be used in front.
			$scopes = array_flip( $acl['acl'] );
			if ( ! isset( $scopes['search'] ) ) {
				return false;
			}
			unset( $scopes['search'] );

			if ( isset( $scopes['settings'] ) ) {
				unset( $scopes['settings'] );
			}

			if ( isset( $scopes['listIndexes'] ) ) {
				unset( $scopes['listIndexes'] );
			}

			// Short circuit ACL checks for local development.
			if ( defined( 'WP_LOCAL_DEV' ) && WP_LOCAL_DEV ) {
				return true;
			}

			// ... the rest of the existing method here....
```

**Comment by richaber** [comment]
@drzraf tested locally and it appears to be working for me, if you'd like to try it out before I merge.
Branch [feature/67-relax-is-valid-search-key](https://github.com/WebDevStudios/wp-search-with-algolia/tree/)

**Comment by richaber** [comment]
Since this appears to be working, I am going to go ahead and merge.
