### ISSUE TITLE
Reports of post content not being indexed

### ISSUE THREAD

**Issue by richaber** [WebDevStudios/wp-search-with-algolia#76]
**Describe the bug**
Getting reports of some installs not indexing the post content.

**Expected behavior**
Post content should be indexed.

**Additional context**
https://wordpress.org/support/topic/content-attribute-empty/
https://wordpress.org/support/topic/not-indexing-the-post-content-automatically/

**Screenshots**
![download](https://user-images.githubusercontent.com/5407441/87184476-add88380-c2ad-11ea-9c74-b3522d73fb40.png)

**Comment by richaber** [comment]
Potentially related:
https://github.com/WebDevStudios/wp-search-with-algolia/issues/57

**Comment by richaber** [comment]
If you are a WP Search with Algolia user, I would be interested in hearing if you are currently experiencing this issue, or have at any point experienced this issue. The more details you can provide to help us determine the root cause, the better.

When did you notice this issue arise?
Did it coincide with a particular release?
What version of WordPress?
What version of PHP?
What version of MySQL?
What plugins are installed?
What theme(s) are you using?
Do you have any customizations?
Does it happen with all post types, or a specific post type?
Have you made sure to “Push Settings” and “Re-index” for each index you have enabled in WP-Admin -> Algolia Search -> Autocomplete?

**Comment by richaber** [comment]
I have been unable to reproduce the issue locally, so would need more details from users who have experienced this.

To test locally, I performed the following...

I created a new Application in the Algolia dashboard to ensure I was not cross-contaminating with previous tests.
I _did not_ create an initial index in Algolia when prompted.

I installed a new local test site to prevent cross-contamination with previous tests, with the following configuration...
* PHP version 7.4.1
* MySQL version 8.0.16
* WordPress 5.4.2 (Single Site, not multisite)
* WP Search with Algolia version 1.3.0
* Twenty Twenty version 1.4

In WP Search with Algolia's Settings screen, I entered the App ID, Search API Key, and Admin API Key, from the new Algolia application I created.

In WP Search with Algolia's Autocomplete screen, I enabled autocomplete, I checked the boxes to enable Posts and Pages, I pushed settings for both, and ran Re-index for both.

In WP Search with Algolia's Search Page screen, I clicked the Use Algolia with Instantsearch.js radio button and saved changes. I was then prompted to index all posts, which I did.

In Algolia's dashboard, I verified that the posts index exists, and contains the "content" of the "Hello World" post.

I then created a new post, to test that the indexing performed as expected on publish, and was able to verify that the new test post was added to the index in Algolia.

![www_algolia_com_apps_50KVC2GGZI_explorer_browse_wp_posts_post__2_](https://user-images.githubusercontent.com/5407441/87190726-9d79d600-c2b8-11ea-9632-65de49044ade.png)

I then performed searches from the front end and verified that the "content" snippet was indeed displaying while searching.
![Screen Shot 2020-07-10 at 2 19 14 PM](https://user-images.githubusercontent.com/5407441/87190707-9357d780-c2b8-11ea-9d24-9b856551ecc1.png)
![Screen Shot 2020-07-10 at 2 19 03 PM](https://user-images.githubusercontent.com/5407441/87190708-93f06e00-c2b8-11ea-833b-3bcd12ac07de.png)
![Screen Shot 2020-07-10 at 2 18 06 PM](https://user-images.githubusercontent.com/5407441/87190709-94890480-c2b8-11ea-88a0-89d006de3350.png)

**Comment by Johntyb** [comment]
**What version of WP Search with Algolia?**
1.3.0
**When did you notice this issue arise?**
Early June 2020
**Did it coincide with a particular WP Search with Algolia release?**
Don't know
**What version of WordPress?**
5.4.2–en_GB (multisite)
**What version of PHP?**
7.2.24-0ubuntu0.18.04.6 (Supports 64bit values)
**What version of MySQL?**
5.7.30-0ubuntu0.18.04.1
**What plugins are installed?**

- https://wordpress.org/plugins/nhsblocks/
- https://wordpress.org/plugins/duracelltomi-google-tag-manager/
- https://wordpress.org/plugins/cookie-notice/
- https://wordpress.org/plugins/gutenberg/
- https://wordpress.org/plugins/members/
- https://wordpress.org/plugins/google-captcha/
- https://wordpress.org/plugins/sendgrid-email-delivery-simplified/
- https://updraftplus.com/
- https://wordpress.org/plugins/wordpress-seo/

**What theme(s) are you using?**
https://wordpress.org/themes/nightingale/
**Do you have any customizations?**
No
**Does it happen with all post types, or a specific post type?**
All
**Have you made sure to “Push Settings” and “Re-index” for each index you have enabled in WP-Admin -> Algolia Search -> Autocomplete?**
Yes
**Does downgrading to a specific release resolve the issue? If so, which release?**
Dont know, havent tried.

**Comment by tw2113** [comment]
Requested the plugin list, but here's what I have now for this thread: https://wordpress.org/support/topic/not-indexing-the-post-content-automatically/

====
Hi Michael,

Thank you for answering my query
Please find below answers to your questions

WordPress 5.4.2
PHP 7.3.19
MySQL 5.7.26
I am using around 19 plugins including Newspaper theme

Yes it happens with also post type but not all the times sometimes this problem is coming, sometimes it is working well

Yes, Push setting and Re-index is enabled From WP-admin side.

**Comment by tw2113** [comment]
Forementioned plugin list

Accelerated Mobile Pages Version 1.0.52 by Ahmed Kaludi, Mohammed Kaludi (Latest version: 1.0.58.4)
Duplicate Post Version 3.2.4 by Enrico Battocchi (Latest version: 3.2.5)
JW Player for WordPress Version 2.0.2 by ilGhera
Newspaper AMP Theme Version 2.0.12 by Mohammed Kaludi, Ahmed Kaludi
Search & Replace Version 3.2.1 by Inpsyde GmbH
Simple Tags Version 2.5.7 by Amaury BALMER
tagDiv Cloud Library Version 1.4 | built on 01.04.2020 8:57 by tagDiv
tagDiv Composer Version 2.5 | built on 01.04.2020 8:57 by tagDiv
tagDiv Newsletter Version 1.5 | built on 15.04.2020 7:19 by tagDiv
tagDiv Standard Pack Version 1.0 BETA | built on 01.04.2020 8:57 by tagDiv
Titan Anti-spam & Security Version 7.0.3 by CreativeMotion (Latest version: 7.1.4)
User Role Editor Version 4.55.1 by Vladimir Garagulya
Visual Form Builder Version 3.0.1 by Matthew Muro
WordPress Importer Version 0.7 by wordpressdotorg
WP All Export Version 1.2.6 by Soflyy
WP File Manager Version 6.4 by mndpsingh287 (Latest version: 6.5)
WP Offload Media Lite Version 2.3.2 by Delicious Brains (Latest version: 2.4)
WP Search with Algolia Version 1.3.0 by WebDevStudios
WPS Hide Login Version 1.5.6 by WPServeur, NicolasKulka, tabrisrp
WP User Avatar Version 2.2.7 by ProfilePress

https://wordpress.org/support/topic/not-indexing-the-post-content-automatically/#post-13124705

**Comment by richaber** [comment]
🤔  I'm not seeing a pattern, so far, between the installed plugins listed in the two reports.

**Comment by richaber** [comment]
@Johntyb I have installed and activated the Nightingale theme, and the publicly available plugins you mentioned (not UpdraftPlus), on a multisite install with "English (UK)" for testing.

```
### wp-core ###

version: 5.4.2
site_language: en_GB
user_language: en_GB
timezone: +00:00
permalink: /blog/%postname%/
https_status: false
user_registration: false
default_comment_status: open
multisite: true
user_count: 1
site_count: 3
network_count: 1
dotorg_communication: true

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Nightingale (nightingale)
version: 2.1.8
author: Tony Blacker, NHS Leadership Academy
author_website: https://www.leadershipacademy.nhs.uk
parent_theme: none
theme_features: automatic-feed-links, title-tag, post-thumbnails, menus, html5, customize-selective-refresh-widgets, custom-logo, editor-styles, wp-block-styles, responsive-embeds, starter-content, disable-custom-colors, editor-color-palette, widgets
theme_path: /app/public/wp-content/themes/nightingale

### wp-themes-inactive (10) ###

Twenty Eleven: version: 3.4, author: the WordPress team
Twenty Fifteen: version: 2.6, author: the WordPress team
Twenty Fourteen: version: 2.8, author: the WordPress team
Twenty Nineteen: version: 1.6, author: the WordPress team
Twenty Seventeen: version: 2.3, author: the WordPress team
Twenty Sixteen: version: 2.1, author: the WordPress team
Twenty Ten: version: 3.0, author: the WordPress team
Twenty Thirteen: version: 3.0, author: the WordPress team
Twenty Twelve: version: 3.1, author: the WordPress team
Twenty Twenty: version: 1.4, author: the WordPress team

### wp-mu-plugins (1) ###

qm-file-path-map: author: (undefined), version: (undefined)

### wp-plugins-active (10) ###

Cookie Notice: version: 1.3.2, author: dFactory
Google Tag Manager for Wordpress: version: 1.11.4, author: Thomas Geiger
Gutenberg: version: 8.5.1, author: Gutenberg Team
Members: version: 3.0.10, author: MemberPress
NHS Blocks: version: 1.1.6, author: Tony Blacker, NHS Leadership Academy
Query Monitor: version: 3.5.2, author: John Blackbourn (latest version: 3.6.0)
reCaptcha by BestWebSoft: version: 1.57, author: BestWebSoft
SendGrid: version: 1.11.8, author: SendGrid
WP Search with Algolia: version: 1.3.0, author: WebDevStudios
Yoast SEO: version: 14.5, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1673
imagemagick_version: ImageMagick 6.8.9-9 Q16 x86_64 2018-05-18 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 4 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 4 GB
	imagick::RESOURCETYPE_MEMORY: 2 GB
	imagick::RESOURCETYPE_THREAD: 2
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.06

### wp-server ###

server_architecture: Linux 4.9.93-boot2docker x86_64
httpd_software: nginx/1.10.1
php_version: 7.2.0 64bit
php_sapi: fpm-fcgi
max_input_variables: 3000
time_limit: 900
memory_limit: 256M
max_input_time: -1
upload_max_size: 1000M
php_post_max_size: 1000M
curl_version: 7.38.0 OpenSSL/1.0.1t
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 5.6.34
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: b396954eeb2d1d9ed7902b8bae237b287f21ad9e $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /app/public/wp-content
WP_PLUGIN_DIR: /app/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: true
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable
```

I don't have the exact same configuration that you have, but in my testing so far, the post content _is_ indexing and searchable as expected.

![Screen Shot 2020-07-17 at 8 03 49 PM](https://user-images.githubusercontent.com/5407441/87841189-32587280-c869-11ea-9c30-166c5b68944d.png)

![Screen Shot 2020-07-17 at 8 02 18 PM](https://user-images.githubusercontent.com/5407441/87841193-397f8080-c869-11ea-89c9-68e511d1a652.png)

Based on that, I don't _think_ it's a plugin or theme conflict. Though you could try disabling all plugins, except WP Search with Algolia, and switch to a default Twenty* theme, then "Push Settings" for each of your enabled Indexes, then "Re-index" for each of your enabled Indexes, and see if that works.

If you have error logging turned on for your installation, are there any PHP errors?

When you re-index from the WP Dashboard, do you see any JS errors in your browser console?

Do you have WP-CLI available? If so, does running `wp algolia reindex --url=<url-of-a-blog-in-the-multisite>` index the `content` properly?

Maybe try using a new, unique, `Index name prefix` in WP-Admin → Algolia Search → Settings? Then in WP-Admin → Algolia Search → Autocomplete, "Push Settings" for each of your enabled Indexes, then "Re-index" for each of your enabled Indexes, and see if that has any impact.

**Comment by Johntyb** [comment]
I reverted to version 1.2 of WP Search with Algolia and this appears to have fixed the problem.
![image](https://user-images.githubusercontent.com/3426135/87851064-15658300-c8ed-11ea-9a06-007e98bb9868.png)

**Comment by richaber** [comment]
Thank you for testing that @Johntyb.

I'll compare [1.2 to 1.3](https://github.com/WebDevStudios/wp-search-with-algolia/compare/1.2.0...1.3.0) to see if I can find any clues as to what might have changed in 1.3 that doesn't work in your environment.

**Comment by richaber** [comment]
I do not see any changes between versions 1.2 and 1.3 that would have an impact on indexing of  a record's `content` attribute.

A few new hooks were added, but that would only affect users that have implemented custom code.
We added additional input sanitization to $_GET and $_POST inputs, unrelated to the actual indexing process.
We prevented accidental re-indexing when a post object is deleted.

As I have been unable to reproduce this issue, I really do need more data from users who experience this, to continue investigating.

I will leave this ticket open, for now, so any users who experience this may provide additional information.

It is possible that some reports may be for "split records", where a record is split into two or more parts, and do not have all the attributes in a single record.

It is possible that some may have posts that do not have actual content in the post_content field (possibly caused by some page builders, custom ACF flex layouts, and the like).

It is possible that some may have posts that are not behaving well with the `Algolia_Utils::remove_content_noise()` [regexes](https://github.com/WebDevStudios/wp-search-with-algolia/blob/1.3.0/includes/class-algolia-utils.php#L122-L157
). I'm not sure I'm a fan of that particular method anyway, so I may change that.

**Comment by megane9988** [comment]
@richaber 

Hello.
I've encountered the same phenomenon as the others, where the content is empty.

Specifically, when I used the Snow Monkey Blocks plugin ( https://wordpress.org/plugins/snow-monkey-blocks/ ) with
It did happen.

I haven't tried anything else. It looks like it could happen when used in conjunction with certain plugins and themes.

**Comment by richaber** [comment]
Thank you for the information @megane9988, 

The Snow Monkey Blocks plugin definitely triggers this issue in my testing.

It appears that `$post_content` is returned as an empty string, when `the_content` filter is applied in [Algolia_Posts_Index::get_post_records()](https://github.com/WebDevStudios/wp-search-with-algolia/blob/6332237e071c40bf622f2facb38a29908a504ea0/includes/indices/class-algolia-posts-index.php#L159) and [Algolia_Searchable_Posts_Index::get_post_records()](https://github.com/WebDevStudios/wp-search-with-algolia/blob/6332237e071c40bf622f2facb38a29908a504ea0/includes/indices/class-algolia-searchable-posts-index.php#L146), when the Snow Monkey Blocks plugin is installed and activated, even when no blocks from the Snow Monkey Blocks plugin are used in the post content.

I'm not 100% certain what the _root cause_ is, but in testing various functions hooked to `the_content`, this appears to be related to when the `do_blocks` function runs on `the_content` hook.

This requires further investigation to see if this is just a compatibility issue with some third-party plugins/themes that we cannot resolve on our side, or, if there's some way for us to adjust how `$post_content` is "rendered" (using that term loosely) before distilling and sending to the index.

**Comment by JMonvoisin** [comment]
I have the same issue, content is empty in Algolia indices. :(

**What version of WP Search with Algolia?**
1.5.0
**When did you notice this issue arise?**
Oct 2020
**Did it coincide with a particular WP Search with Algolia release?**
Don't know
**What version of WordPress?**
5.5.1
**What version of PHP?**
7.4.7
**What version of MySQL?**
7.4.7
**What plugins are installed?**
Akismet Anti-Spam
AMP
Async JavaScript
Classic Editor
Contact Form 7
Defender
Grow by Mediavine
Hummingbird
Infinite Scroll and Load More Ajax Pagination
Plugins Condition
reBusted!
Redirection
Smush
Sticky Posts - Switch
TablePress
WP Cloudflare Super Page Cache
WP Mail SMTP
WP Search with Algolia
Yoast Duplicate Post
Yoast SEO
**What theme(s) are you using?**
Twenty Fifteen 2.7
**Do you have any customizations?**
Yes
**Does it happen with all post types, or a specific post type?**
All
**Have you made sure to “Push Settings” and “Re-index” for each index you have enabled in WP-Admin -> Algolia Search -> Autocomplete?**
Yes
**Does downgrading to a specific release resolve the issue? If so, which release?**
No

**Comment by JMonvoisin** [comment]
Please note the issue persists (on my install) with every plugin disabled and native untouched Twenty-Fifteen theme.
Laos tried reverting to previous version of Algolia Search plugin. :s

**Comment by richaber** [comment]
Closing. This doesn't appear to be widespread enough to call it a bug in WPSWA. Every confirmed case of this issue that has been investigated has been related to other plugins or themes interfering with WPSWA content indexing.
