### ISSUE TITLE
I want you to be able to set facetingAfterDistinct.

### ISSUE THREAD

**Issue by kusokamayarou** [WebDevStudios/wp-search-with-algolia#85]
**Is your feature request related to a problem? Please describe.**
I want to set facetingAfterDistinct.

**Describe the solution you'd like**
I don't want to display different number of records in Algolia's Index.

**Describe alternatives you've considered**
Currently, facetingAfterDistinct is set on the client side to correct the incorrect record count.

**Additional context**
![FireShot Capture 461 - Indices - Algolia - www algolia com](https://user-images.githubusercontent.com/25380796/89983522-a3e1e000-dcb2-11ea-8597-f375dce78d36.png)

**Comment by richaber** [comment]
Howdy @kusokamayarou, 

> I want to set facetingAfterDistinct.

Could you provide a little more information about _where_ you want to set `facetingAfterDistinct`?  

I believe we have it set by default in the [`templates/instantsearch.php` partial](https://github.com/WebDevStudios/wp-search-with-algolia/blob/6332237e071c40bf622f2facb38a29908a504ea0/templates/instantsearch.php#L75).

The PHP Client can use `facetingAfterDistinct` too, though I don't think we currently have that set as a default param (which makes me think we might want to add that).

If the PHP Client is where you need it (for the "Use Algolia in the backend" search page setting), I believe you can use the [`algolia_search_params` filter ](https://github.com/WebDevStudios/wp-search-with-algolia/blob/6332237e071c40bf622f2facb38a29908a504ea0/includes/class-algolia-search.php#L116-L142) to add that param.

Something like this (untested) should work for that scenario...
```
/**
 * Filter the array of parameters used by the Algolia PHP Client for Index search.
 *
 * @param array $params Parameters for the Algolia PHP Client to use for Index search.
 *
 * @return array
 */
function my_algolia_search_params( $params ) {

	$params['facetingAfterDistinct'] = true;

	return $params;
}

add_filter( 'algolia_search_params', 'my_algolia_search_params' );
```

> I don't want to display different number of records in Algolia's Index.

We do not control the number of records displayed in the Algolia Dashboard.

> Currently, facetingAfterDistinct is set on the client side to correct the incorrect record count.

Yes, the `facetingAfterDistinct` parameter is set on an Algolia _client_ when _searching an index_, to calculate faceting after de-duplication has been applied. From the [`facetingAfterDistinct` documentation](https://www.algolia.com/doc/api-reference/api-parameters/facetingAfterDistinct/):

> When using the [`distinct`](https://www.algolia.com/doc/api-reference/api-parameters/distinct/) setting in combination with faceting, facet counts may be higher than expected. This is because the engine, by default, computes faceting before applying de-duplication (`distinct`). When `facetingAfterDistinct` is set to true, the engine calculates faceting after the de-duplication has been applied.

> `facetingAfterDistinct` can only be set at query time; it can’t be added as a default setting of the index.

**Comment by kusokamayarou** [comment]
I understood. Thanks.
