### ISSUE TITLE
GTM ( Google Tag Manager ) support

### ISSUE THREAD

**Issue by richaber** [WebDevStudios/wp-search-with-algolia#86]
@JonnyHayes has opened PR #84 "Adds classnames to links. Mainly for GTM purposes"

Related WPORG Forum thread: https://wordpress.org/support/topic/extending-the-search-2/

Algolia GTM docs: https://www.algolia.com/doc/guides/getting-insights-and-analytics/connectors/google-tag-manager/#setup

**Comment by richaber** [comment]
Howdy @JonnyHayes, 

Since I'm not familiar with how Google Tag Manager and Algolia work together, can you provide a little explanation for how your proposed PR "fix(es) it enough for most people to be able to use instant search with GTM out of the box"?

**Comment by JonnyHayes** [comment]
Aloha richaber <https://github.com/richaber/richaber> ,

GTM needs a named "trigger"   e.g. a class  on an element / link etc .
By giving the element(s) I changed a class name we have something that GTM
can use.
It's pretty easy to set up GTM to test. If you want I can do a
screenshare to demo.
See attached screen grabs of how I set up GTM:
Cheers
Jon

ᐧ

**Comment by filip-van-hoeckel** [comment]
Any option to indeed see that screenshare or any other documentation for this issue? I have clicks working using the custom class, but ideally feed all data back to Algolia as well - and see what term caused the click to begin with. Thanks in advance.
