### ISSUE TITLE
Push Settings button is dangerous!

### ISSUE THREAD

**Issue by edirpedro** [WebDevStudios/wp-search-with-algolia#89]
The Push Setting button at the plugin Search Page can erase all settings made at Algolia control panel if pressed. So it needs to alert about this before someone pushes that button.

I had made some configurations at Algolia and then clicked on that "Push Settings" button to see what it does. Nothing happend! But then I look at Algolia on the configuration tab and saw that all my configurations is lost. 😅

**Comment by tw2113** [comment]
Agreed on this topic. Messaging of some sort, whether it's a browser alert, or even just a message the tops of pages would be a good thing here.
