### ISSUE TITLE
Possible ideia to support Woocommerce

### ISSUE THREAD

**Issue by edirpedro** [WebDevStudios/wp-search-with-algolia#94]
This is a solution I found to make this plugin provides search to Woocommerce. I tested with WP 5.5 and WC 4.4 with defaults widgets only and it works good. Some information:

- The ideia is to search with Algolia and then pass the results to Woocommerce filter that content using the `post__in` attribute on WP_Query.
- It works disabling Algolia for Search Page, because the plugin replaces the query completly and it breaks woocommerce.
- Only a single indice is acceptable, it could be the `searchable_posts` but as I disabled it, the plugin won't index it for me so I changed to `posts_product` to let the plugin continue indexing it. In my store the autocomplete is enabled with this indice.
- The attribute `attributesToRetrieve` it not working and I don't know why. It would make json smaller and fast to retrieve.
- It only returns 1000 results because is the Algolia limit, but for searches, this is enough to find what you want on the list and even filter the list.
- I can't use Algolia to paginate because Woocommerce has widgets to filter the product list and it needs a full search result to build the options in those filters. It'll be based on 1000 products found on that search.
- The option Relevance in the ordering filter on Woocommerce is changed to reflect the ordering as in Algolia results.
- And the `posts_search` needs to be empty because it searches again on post title, excerpt and content with the Algolia results indicated in  `post__in` variable.

I don't know if this could be implemented on this plugin, but at least the ideia can be checked and some hooks could be added to this plugin to make this work simpler. For example, instead of disabling Algolia on Search Page, a Hook could let me do a short circuit and run my own search, then I could use the `searchable_posts` indice indexed by the plugin.

**File: functions.php**
```
/*
* Search with Algolia and deliver it to Woocommerce to filter the content
* IMPORTANT: set "Do not use Algolia" for Search Page setting
***********************************************************************/

add_action( 'pre_get_posts', function( $query ) {
	
	global $algolia;

	// Nothing to do if inside admin, is not main query or Algolia plugin is not available
		
	if ( empty($algolia) || is_admin() || ! $query->is_main_query() )
		return $query;	

	// Search
	
	$search = get_option( 'algolia_override_native_search', 'native' );
			
	if ( $search == 'native' && is_search() && is_shop() ) {

		// Indice
		
		$indices = $algolia->get_indices( [ 'enabled' => true ] );
		$index = null;
		
		foreach( $indices as $indice ) {
			if ( $indice->get_id() == 'posts_product' ) // only a single indice
				$index = $indice->get_index();
		}
			
		if ( $index ) {
			
			// Searching with Algolia, configurations stay at Algolia control panel
			
			$params = [
				'attributesToRetrieve' 	=> [ 'post_id' ], // Not working ???
				'hitsPerPage'          	=> 1000, // Algolia limit, but it's enough for searches
				'page'				=> 0, // Algolia pages are zero indexed
			];
			
			$results = [];
				
			try {
				
				$results = $index->search( $query->query['s'], $params );
				
			} catch ( Exception $e ) {
				
				error_log( $e->getMessage() );
				return;
				
			}
			
			if ( ! empty($results['hits']) ) {
				
				// Setting up Algolia results
			
				$query->set( 'post__in', array_column( $results['hits'], 'post_id' ) );
			
				// Changing default "relevance" ordering to reflect Algolia ordering
				
				if ( 'relevance' == $query->get('orderby') ) {
					$query->set( 'orderby', 'post__in' );
					$query->set( 'order', 'DESC' );
				}
								
			}
		
		}
						
	}
	
	return $query;

}, 99, 1 );

// Disable default search to not search again into post_title, post_excerpt and post_content
// Only widget filters will be enabled in the wp search

add_filter( 'posts_search', function( $request ) {

	global $algolia;
		
	$search = get_option( 'algolia_override_native_search', 'native' );

	if ( ! empty($algolia) && is_shop() && $search == 'native' )
		$request = '';

	return $request;
	
}, 10, 1 );
```

**Comment by richaber** [comment]
Closing this issue as WP Search with Algolia (WPSWA) does not provide any specific support for any e-commerce plugin.
