### ISSUE TITLE
Limit amount of records indexed per post type

### ISSUE THREAD

**Issue by claytoncollie** [WebDevStudios/wp-search-with-algolia#95]
**Is your feature request related to a problem? Please describe.**
I host my client sites on WP Engine which comes with three environments and then my team of developers have their own local environments. Each env gets their own set of indexes and each developer has their own indexes all on the same App in Algolia.  For some of the larger sites, it is very hard to fit all of those onto a single app without going over the 10k limit especially if you have multiple replicas.

**Describe the solution you'd like**
I would like to see a filterable limit of posts indexed (possibly per post type) depending on the site environment. As of WP 5.5.1, we can use `wp_get_environment_type` to distinguish where we are indexing. Say if you are on `production` or `staging`, you don't have a limit but if you are on `local` or `development`, you limit each post type to only index 20 or 50 posts.

**Describe alternatives you've considered**
This is more of a question. I am really asking to see where it could be accomplished in the codebase.

**Comment by edirpedro** [comment]
There are some hooks available you can use to abort indexing. Take a look at this idea:

Hooks:
```
algolia_should_index_post
algolia_should_index_searchable_post
algolia_should_index_term
algolia_should_index_user
```

Ideia to stop at count 10:
```
add_filter( 'algolia_should_index_post', function( $should_index, $item ) {
	
	global $algolia_should_index_post;
	$algolia_should_index_post++;
	
	return $algolia_should_index_post <= 10;
	
} );
```

**Comment by claytoncollie** [comment]
@edirpedro This is a great little idea. Thank you. 

Small fix: your last line needs `}, 10, 2 );`
