### ISSUE TITLE
Restrict search to only show results from certain algolia indexes

### ISSUE THREAD

**Issue by liammaurer** [WebDevStudios/wp-search-with-algolia#96]
**Is your feature request related to a problem? Please describe.**
I want to allow users to only be able to search from certain CPT's on certain pages and other CPT's on other pages. 

**Describe the solution you'd like**
It would be nice if there was a way to restrict the type of posts that show when a user searches based on pre-defined settings.

**Comment by richaber** [comment]
Howdy @liammaurer,

That sounds like a pretty custom request, and would likely require a pretty custom implementation.

You can achieve something like that for yourself with custom code, but it would be outside the bounds of what this plugin can offer out-of-the-box.
